// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: reservation/v1/reservation.proto

package reservationv1

import (
	v11 "github.com/ekkx/tcmrsv-web/internal/shared/pb/room/v1"
	v1 "github.com/ekkx/tcmrsv-web/internal/shared/pb/user/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Reservation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OfficialSiteId *string                `protobuf:"bytes,2,opt,name=official_site_id,json=officialSiteId,proto3,oneof" json:"official_site_id,omitempty"`
	User           *v1.User               `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	CampusType     v11.CampusType         `protobuf:"varint,4,opt,name=campus_type,json=campusType,proto3,enum=room.v1.CampusType" json:"campus_type,omitempty"`
	Room           *v11.Room              `protobuf:"bytes,5,opt,name=room,proto3" json:"room,omitempty"`
	Date           string                 `protobuf:"bytes,6,opt,name=date,proto3" json:"date,omitempty"`
	FromHour       int32                  `protobuf:"varint,7,opt,name=from_hour,json=fromHour,proto3" json:"from_hour,omitempty"`
	FromMinute     int32                  `protobuf:"varint,8,opt,name=from_minute,json=fromMinute,proto3" json:"from_minute,omitempty"`
	ToHour         int32                  `protobuf:"varint,9,opt,name=to_hour,json=toHour,proto3" json:"to_hour,omitempty"`
	ToMinute       int32                  `protobuf:"varint,10,opt,name=to_minute,json=toMinute,proto3" json:"to_minute,omitempty"`
	CreateTime     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Reservation) Reset() {
	*x = Reservation{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reservation) ProtoMessage() {}

func (x *Reservation) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reservation.ProtoReflect.Descriptor instead.
func (*Reservation) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{0}
}

func (x *Reservation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Reservation) GetOfficialSiteId() string {
	if x != nil && x.OfficialSiteId != nil {
		return *x.OfficialSiteId
	}
	return ""
}

func (x *Reservation) GetUser() *v1.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Reservation) GetCampusType() v11.CampusType {
	if x != nil {
		return x.CampusType
	}
	return v11.CampusType(0)
}

func (x *Reservation) GetRoom() *v11.Room {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *Reservation) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Reservation) GetFromHour() int32 {
	if x != nil {
		return x.FromHour
	}
	return 0
}

func (x *Reservation) GetFromMinute() int32 {
	if x != nil {
		return x.FromMinute
	}
	return 0
}

func (x *Reservation) GetToHour() int32 {
	if x != nil {
		return x.ToHour
	}
	return 0
}

func (x *Reservation) GetToMinute() int32 {
	if x != nil {
		return x.ToMinute
	}
	return 0
}

func (x *Reservation) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type GetReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReservationRequest) Reset() {
	*x = GetReservationRequest{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReservationRequest) ProtoMessage() {}

func (x *GetReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReservationRequest.ProtoReflect.Descriptor instead.
func (*GetReservationRequest) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{1}
}

func (x *GetReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type GetReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservation   *Reservation           `protobuf:"bytes,1,opt,name=reservation,proto3" json:"reservation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReservationResponse) Reset() {
	*x = GetReservationResponse{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReservationResponse) ProtoMessage() {}

func (x *GetReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReservationResponse.ProtoReflect.Descriptor instead.
func (*GetReservationResponse) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{2}
}

func (x *GetReservationResponse) GetReservation() *Reservation {
	if x != nil {
		return x.Reservation
	}
	return nil
}

type ListReservationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReservationsRequest) Reset() {
	*x = ListReservationsRequest{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReservationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReservationsRequest) ProtoMessage() {}

func (x *ListReservationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReservationsRequest.ProtoReflect.Descriptor instead.
func (*ListReservationsRequest) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{3}
}

type ListReservationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservations  []*Reservation         `protobuf:"bytes,1,rep,name=reservations,proto3" json:"reservations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReservationsResponse) Reset() {
	*x = ListReservationsResponse{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReservationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReservationsResponse) ProtoMessage() {}

func (x *ListReservationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReservationsResponse.ProtoReflect.Descriptor instead.
func (*ListReservationsResponse) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{4}
}

func (x *ListReservationsResponse) GetReservations() []*Reservation {
	if x != nil {
		return x.Reservations
	}
	return nil
}

type CreateReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampusType    v11.CampusType         `protobuf:"varint,1,opt,name=campus_type,json=campusType,proto3,enum=room.v1.CampusType" json:"campus_type,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	FromHour      int32                  `protobuf:"varint,3,opt,name=from_hour,json=fromHour,proto3" json:"from_hour,omitempty"`
	FromMinute    int32                  `protobuf:"varint,4,opt,name=from_minute,json=fromMinute,proto3" json:"from_minute,omitempty"`
	ToHour        int32                  `protobuf:"varint,5,opt,name=to_hour,json=toHour,proto3" json:"to_hour,omitempty"`
	ToMinute      int32                  `protobuf:"varint,6,opt,name=to_minute,json=toMinute,proto3" json:"to_minute,omitempty"`
	RoomId        string                 `protobuf:"bytes,7,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReservationRequest) Reset() {
	*x = CreateReservationRequest{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReservationRequest) ProtoMessage() {}

func (x *CreateReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReservationRequest.ProtoReflect.Descriptor instead.
func (*CreateReservationRequest) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{5}
}

func (x *CreateReservationRequest) GetCampusType() v11.CampusType {
	if x != nil {
		return x.CampusType
	}
	return v11.CampusType(0)
}

func (x *CreateReservationRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CreateReservationRequest) GetFromHour() int32 {
	if x != nil {
		return x.FromHour
	}
	return 0
}

func (x *CreateReservationRequest) GetFromMinute() int32 {
	if x != nil {
		return x.FromMinute
	}
	return 0
}

func (x *CreateReservationRequest) GetToHour() int32 {
	if x != nil {
		return x.ToHour
	}
	return 0
}

func (x *CreateReservationRequest) GetToMinute() int32 {
	if x != nil {
		return x.ToMinute
	}
	return 0
}

func (x *CreateReservationRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type CreateReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservation   *Reservation           `protobuf:"bytes,1,opt,name=reservation,proto3" json:"reservation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReservationResponse) Reset() {
	*x = CreateReservationResponse{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReservationResponse) ProtoMessage() {}

func (x *CreateReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReservationResponse.ProtoReflect.Descriptor instead.
func (*CreateReservationResponse) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{6}
}

func (x *CreateReservationResponse) GetReservation() *Reservation {
	if x != nil {
		return x.Reservation
	}
	return nil
}

type DeleteReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReservationRequest) Reset() {
	*x = DeleteReservationRequest{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReservationRequest) ProtoMessage() {}

func (x *DeleteReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReservationRequest.ProtoReflect.Descriptor instead.
func (*DeleteReservationRequest) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type DeleteReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReservationResponse) Reset() {
	*x = DeleteReservationResponse{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReservationResponse) ProtoMessage() {}

func (x *DeleteReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReservationResponse.ProtoReflect.Descriptor instead.
func (*DeleteReservationResponse) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{8}
}

var File_reservation_v1_reservation_proto protoreflect.FileDescriptor

const file_reservation_v1_reservation_proto_rawDesc = "" +
	"\n" +
	" reservation/v1/reservation.proto\x12\x0ereservation.v1\x1a\x12room/v1/room.proto\x1a\x12user/v1/user.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa2\x03\n" +
	"\vReservation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x10official_site_id\x18\x02 \x01(\tH\x00R\x0eofficialSiteId\x88\x01\x01\x12!\n" +
	"\x04user\x18\x03 \x01(\v2\r.user.v1.UserR\x04user\x124\n" +
	"\vcampus_type\x18\x04 \x01(\x0e2\x13.room.v1.CampusTypeR\n" +
	"campusType\x12!\n" +
	"\x04room\x18\x05 \x01(\v2\r.room.v1.RoomR\x04room\x12\x12\n" +
	"\x04date\x18\x06 \x01(\tR\x04date\x12\x1b\n" +
	"\tfrom_hour\x18\a \x01(\x05R\bfromHour\x12\x1f\n" +
	"\vfrom_minute\x18\b \x01(\x05R\n" +
	"fromMinute\x12\x17\n" +
	"\ato_hour\x18\t \x01(\x05R\x06toHour\x12\x1b\n" +
	"\tto_minute\x18\n" +
	" \x01(\x05R\btoMinute\x12;\n" +
	"\vcreate_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTimeB\x13\n" +
	"\x11_official_site_id\">\n" +
	"\x15GetReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"W\n" +
	"\x16GetReservationResponse\x12=\n" +
	"\vreservation\x18\x01 \x01(\v2\x1b.reservation.v1.ReservationR\vreservation\"\x19\n" +
	"\x17ListReservationsRequest\"[\n" +
	"\x18ListReservationsResponse\x12?\n" +
	"\freservations\x18\x01 \x03(\v2\x1b.reservation.v1.ReservationR\freservations\"\xf1\x01\n" +
	"\x18CreateReservationRequest\x124\n" +
	"\vcampus_type\x18\x01 \x01(\x0e2\x13.room.v1.CampusTypeR\n" +
	"campusType\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x1b\n" +
	"\tfrom_hour\x18\x03 \x01(\x05R\bfromHour\x12\x1f\n" +
	"\vfrom_minute\x18\x04 \x01(\x05R\n" +
	"fromMinute\x12\x17\n" +
	"\ato_hour\x18\x05 \x01(\x05R\x06toHour\x12\x1b\n" +
	"\tto_minute\x18\x06 \x01(\x05R\btoMinute\x12\x17\n" +
	"\aroom_id\x18\a \x01(\tR\x06roomId\"Z\n" +
	"\x19CreateReservationResponse\x12=\n" +
	"\vreservation\x18\x01 \x01(\v2\x1b.reservation.v1.ReservationR\vreservation\"A\n" +
	"\x18DeleteReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"\x1b\n" +
	"\x19DeleteReservationResponse2\xb0\x03\n" +
	"\x12ReservationService\x12_\n" +
	"\x0eGetReservation\x12%.reservation.v1.GetReservationRequest\x1a&.reservation.v1.GetReservationResponse\x12e\n" +
	"\x10ListReservations\x12'.reservation.v1.ListReservationsRequest\x1a(.reservation.v1.ListReservationsResponse\x12h\n" +
	"\x11CreateReservation\x12(.reservation.v1.CreateReservationRequest\x1a).reservation.v1.CreateReservationResponse\x12h\n" +
	"\x11DeleteReservation\x12(.reservation.v1.DeleteReservationRequest\x1a).reservation.v1.DeleteReservationResponseB\xcb\x01\n" +
	"\x12com.reservation.v1B\x10ReservationProtoP\x01ZJgithub.com/ekkx/tcmrsv-web/internal/shared/pb/reservation/v1;reservationv1\xa2\x02\x03RXX\xaa\x02\x0eReservation.V1\xca\x02\x0eReservation\\V1\xe2\x02\x1aReservation\\V1\\GPBMetadata\xea\x02\x0fReservation::V1b\x06proto3"

var (
	file_reservation_v1_reservation_proto_rawDescOnce sync.Once
	file_reservation_v1_reservation_proto_rawDescData []byte
)

func file_reservation_v1_reservation_proto_rawDescGZIP() []byte {
	file_reservation_v1_reservation_proto_rawDescOnce.Do(func() {
		file_reservation_v1_reservation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reservation_v1_reservation_proto_rawDesc), len(file_reservation_v1_reservation_proto_rawDesc)))
	})
	return file_reservation_v1_reservation_proto_rawDescData
}

var file_reservation_v1_reservation_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_reservation_v1_reservation_proto_goTypes = []any{
	(*Reservation)(nil),               // 0: reservation.v1.Reservation
	(*GetReservationRequest)(nil),     // 1: reservation.v1.GetReservationRequest
	(*GetReservationResponse)(nil),    // 2: reservation.v1.GetReservationResponse
	(*ListReservationsRequest)(nil),   // 3: reservation.v1.ListReservationsRequest
	(*ListReservationsResponse)(nil),  // 4: reservation.v1.ListReservationsResponse
	(*CreateReservationRequest)(nil),  // 5: reservation.v1.CreateReservationRequest
	(*CreateReservationResponse)(nil), // 6: reservation.v1.CreateReservationResponse
	(*DeleteReservationRequest)(nil),  // 7: reservation.v1.DeleteReservationRequest
	(*DeleteReservationResponse)(nil), // 8: reservation.v1.DeleteReservationResponse
	(*v1.User)(nil),                   // 9: user.v1.User
	(v11.CampusType)(0),               // 10: room.v1.CampusType
	(*v11.Room)(nil),                  // 11: room.v1.Room
	(*timestamppb.Timestamp)(nil),     // 12: google.protobuf.Timestamp
}
var file_reservation_v1_reservation_proto_depIdxs = []int32{
	9,  // 0: reservation.v1.Reservation.user:type_name -> user.v1.User
	10, // 1: reservation.v1.Reservation.campus_type:type_name -> room.v1.CampusType
	11, // 2: reservation.v1.Reservation.room:type_name -> room.v1.Room
	12, // 3: reservation.v1.Reservation.create_time:type_name -> google.protobuf.Timestamp
	0,  // 4: reservation.v1.GetReservationResponse.reservation:type_name -> reservation.v1.Reservation
	0,  // 5: reservation.v1.ListReservationsResponse.reservations:type_name -> reservation.v1.Reservation
	10, // 6: reservation.v1.CreateReservationRequest.campus_type:type_name -> room.v1.CampusType
	0,  // 7: reservation.v1.CreateReservationResponse.reservation:type_name -> reservation.v1.Reservation
	1,  // 8: reservation.v1.ReservationService.GetReservation:input_type -> reservation.v1.GetReservationRequest
	3,  // 9: reservation.v1.ReservationService.ListReservations:input_type -> reservation.v1.ListReservationsRequest
	5,  // 10: reservation.v1.ReservationService.CreateReservation:input_type -> reservation.v1.CreateReservationRequest
	7,  // 11: reservation.v1.ReservationService.DeleteReservation:input_type -> reservation.v1.DeleteReservationRequest
	2,  // 12: reservation.v1.ReservationService.GetReservation:output_type -> reservation.v1.GetReservationResponse
	4,  // 13: reservation.v1.ReservationService.ListReservations:output_type -> reservation.v1.ListReservationsResponse
	6,  // 14: reservation.v1.ReservationService.CreateReservation:output_type -> reservation.v1.CreateReservationResponse
	8,  // 15: reservation.v1.ReservationService.DeleteReservation:output_type -> reservation.v1.DeleteReservationResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_reservation_v1_reservation_proto_init() }
func file_reservation_v1_reservation_proto_init() {
	if File_reservation_v1_reservation_proto != nil {
		return
	}
	file_reservation_v1_reservation_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reservation_v1_reservation_proto_rawDesc), len(file_reservation_v1_reservation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reservation_v1_reservation_proto_goTypes,
		DependencyIndexes: file_reservation_v1_reservation_proto_depIdxs,
		MessageInfos:      file_reservation_v1_reservation_proto_msgTypes,
	}.Build()
	File_reservation_v1_reservation_proto = out.File
	file_reservation_v1_reservation_proto_goTypes = nil
	file_reservation_v1_reservation_proto_depIdxs = nil
}
