services:
  api-test:
    container_name: api-test
    build:
      context: ./docker/api/test
      dockerfile: Dockerfile
    ports:
      - 50052:50052
    volumes:
      - .:/api
    env_file:
      - ./server/.env.test
    depends_on:
      - db-test
  db-test:
    container_name: db-test
    image: postgres:15
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - TZ="Asia/Tokyo"
    command: ["postgres", "-p", "5433"]
    ports:
      - 5433:5433

