// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: create_user.sql

package database

import (
	"context"

	"github.com/ekkx/tcmrsv-web/pkg/ulid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO
    users (
        id,
        password,
        official_site_id,
        official_site_password,
        master_user_id,
        display_name,
        create_time
    )
VALUES
    (
        $1::ulid,
        $2::TEXT,
        $3::TEXT,
        $4::TEXT,
        $5::ulid,
        $6::TEXT,
        NOW()
    )
RETURNING users.id
`

type CreateUserParams struct {
	ID                   ulid.ULID  `json:"id"`
	Password             string     `json:"password"`
	OfficialSiteID       *string    `json:"official_site_id"`
	OfficialSitePassword *string    `json:"official_site_password"`
	MasterUserID         *ulid.ULID `json:"master_user_id"`
	DisplayName          string     `json:"display_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (ulid.ULID, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Password,
		arg.OfficialSiteID,
		arg.OfficialSitePassword,
		arg.MasterUserID,
		arg.DisplayName,
	)
	var id ulid.ULID
	err := row.Scan(&id)
	return id, err
}
