// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: delete_user_by_id.sql

package database

import (
	"context"

	"github.com/ekkx/tcmrsv-web/pkg/ulid"
)

const deleteUserByID = `-- name: DeleteUserByID :one
DELETE FROM
    users
WHERE
    users.id = $1::ulid
RETURNING 1
`

func (q *Queries) DeleteUserByID(ctx context.Context, userID ulid.ULID) (int32, error) {
	row := q.db.QueryRow(ctx, deleteUserByID, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
