// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_user_id_by_official_site_id.sql

package database

import (
	"context"

	"github.com/ekkx/tcmrsv-web/pkg/ulid"
)

const getUserIDByOfficialSiteID = `-- name: GetUserIDByOfficialSiteID :one
SELECT
    users.id
FROM
    users
WHERE
    users.official_site_id = $1::TEXT
`

func (q *Queries) GetUserIDByOfficialSiteID(ctx context.Context, officialSiteID string) (ulid.ULID, error) {
	row := q.db.QueryRow(ctx, getUserIDByOfficialSiteID, officialSiteID)
	var id ulid.ULID
	err := row.Scan(&id)
	return id, err
}
