// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: create_user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO
    users (
        id,
        encrypted_password
    )
VALUES
    (
        $1::text,
        $2::text
    )
RETURNING
    users.id
`

type CreateUserParams struct {
	ID                string `json:"id"`
	EncryptedPassword string `json:"encrypted_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (string, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.EncryptedPassword)
	var id string
	err := row.Scan(&id)
	return id, err
}
