// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: delete_reservation_by_id.sql

package db

import (
	"context"
)

const deleteReservationByID = `-- name: DeleteReservationByID :one
DELETE FROM
    reservations
WHERE
    id = $1::int
RETURNING 1
`

func (q *Queries) DeleteReservationByID(ctx context.Context, reservationID int32) (int32, error) {
	row := q.db.QueryRow(ctx, deleteReservationByID, reservationID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
