// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_user.sql

package db

import (
	"context"
)

const getUserByStudentID = `-- name: GetUserByStudentID :one
SELECT
    users.id,
    users.encrypted_password
FROM
    users
WHERE
    users.id = $1::text
`

func (q *Queries) GetUserByStudentID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByStudentID, id)
	var i User
	err := row.Scan(&i.ID, &i.EncryptedPassword)
	return i, err
}
