// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Reservation struct {
	ID         string             `json:"id"`
	UserID     string             `json:"user_id"`
	RoomID     string             `json:"room_id"`
	Date       pgtype.Timestamptz `json:"date"`
	FromHour   int32              `json:"from_hour"`
	FromMinute int32              `json:"from_minute"`
	ToHour     int32              `json:"to_hour"`
	ToMinute   int32              `json:"to_minute"`
	BookerName *string            `json:"booker_name"`
}

type User struct {
	ID                string `json:"id"`
	EncryptedPassword string `json:"encrypted_password"`
}
