// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CheckReservationConflict(ctx context.Context, arg CheckReservationConflictParams) (bool, error)
	CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (string, error)
	GetMyReservations(ctx context.Context, arg GetMyReservationsParams) ([]Reservation, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
