// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (string, error)
	GetUserByStudentID(ctx context.Context, id string) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
