// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: v1/reservation/reservation.proto

package reservation

import (
	room "github.com/ekkx/tcmrsv-web/server/internal/shared/api/v1/room"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Reservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ExternalId    *string                `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3,oneof" json:"external_id,omitempty"`
	CampusType    room.CampusType        `protobuf:"varint,3,opt,name=campus_type,json=campusType,proto3,enum=room.v1.CampusType" json:"campus_type,omitempty"`
	Date          *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	RoomId        string                 `protobuf:"bytes,5,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	FromHour      int32                  `protobuf:"varint,6,opt,name=from_hour,json=fromHour,proto3" json:"from_hour,omitempty"`
	FromMinute    int32                  `protobuf:"varint,7,opt,name=from_minute,json=fromMinute,proto3" json:"from_minute,omitempty"`
	ToHour        int32                  `protobuf:"varint,8,opt,name=to_hour,json=toHour,proto3" json:"to_hour,omitempty"`
	ToMinute      int32                  `protobuf:"varint,9,opt,name=to_minute,json=toMinute,proto3" json:"to_minute,omitempty"`
	BookerName    *string                `protobuf:"bytes,10,opt,name=booker_name,json=bookerName,proto3,oneof" json:"booker_name,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reservation) Reset() {
	*x = Reservation{}
	mi := &file_v1_reservation_reservation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reservation) ProtoMessage() {}

func (x *Reservation) ProtoReflect() protoreflect.Message {
	mi := &file_v1_reservation_reservation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reservation.ProtoReflect.Descriptor instead.
func (*Reservation) Descriptor() ([]byte, []int) {
	return file_v1_reservation_reservation_proto_rawDescGZIP(), []int{0}
}

func (x *Reservation) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Reservation) GetExternalId() string {
	if x != nil && x.ExternalId != nil {
		return *x.ExternalId
	}
	return ""
}

func (x *Reservation) GetCampusType() room.CampusType {
	if x != nil {
		return x.CampusType
	}
	return room.CampusType(0)
}

func (x *Reservation) GetDate() *timestamp.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Reservation) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Reservation) GetFromHour() int32 {
	if x != nil {
		return x.FromHour
	}
	return 0
}

func (x *Reservation) GetFromMinute() int32 {
	if x != nil {
		return x.FromMinute
	}
	return 0
}

func (x *Reservation) GetToHour() int32 {
	if x != nil {
		return x.ToHour
	}
	return 0
}

func (x *Reservation) GetToMinute() int32 {
	if x != nil {
		return x.ToMinute
	}
	return 0
}

func (x *Reservation) GetBookerName() string {
	if x != nil && x.BookerName != nil {
		return *x.BookerName
	}
	return ""
}

func (x *Reservation) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId int64                  `protobuf:"varint,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReservationRequest) Reset() {
	*x = GetReservationRequest{}
	mi := &file_v1_reservation_reservation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReservationRequest) ProtoMessage() {}

func (x *GetReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_reservation_reservation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReservationRequest.ProtoReflect.Descriptor instead.
func (*GetReservationRequest) Descriptor() ([]byte, []int) {
	return file_v1_reservation_reservation_proto_rawDescGZIP(), []int{1}
}

func (x *GetReservationRequest) GetReservationId() int64 {
	if x != nil {
		return x.ReservationId
	}
	return 0
}

type GetReservationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservation   *Reservation           `protobuf:"bytes,1,opt,name=reservation,proto3" json:"reservation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReservationReply) Reset() {
	*x = GetReservationReply{}
	mi := &file_v1_reservation_reservation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReservationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReservationReply) ProtoMessage() {}

func (x *GetReservationReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_reservation_reservation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReservationReply.ProtoReflect.Descriptor instead.
func (*GetReservationReply) Descriptor() ([]byte, []int) {
	return file_v1_reservation_reservation_proto_rawDescGZIP(), []int{2}
}

func (x *GetReservationReply) GetReservation() *Reservation {
	if x != nil {
		return x.Reservation
	}
	return nil
}

type GetUserReservationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReservationsRequest) Reset() {
	*x = GetUserReservationsRequest{}
	mi := &file_v1_reservation_reservation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReservationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReservationsRequest) ProtoMessage() {}

func (x *GetUserReservationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_reservation_reservation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReservationsRequest.ProtoReflect.Descriptor instead.
func (*GetUserReservationsRequest) Descriptor() ([]byte, []int) {
	return file_v1_reservation_reservation_proto_rawDescGZIP(), []int{3}
}

type GetUserReservationsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservations  []*Reservation         `protobuf:"bytes,1,rep,name=reservations,proto3" json:"reservations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReservationsReply) Reset() {
	*x = GetUserReservationsReply{}
	mi := &file_v1_reservation_reservation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReservationsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReservationsReply) ProtoMessage() {}

func (x *GetUserReservationsReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_reservation_reservation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReservationsReply.ProtoReflect.Descriptor instead.
func (*GetUserReservationsReply) Descriptor() ([]byte, []int) {
	return file_v1_reservation_reservation_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserReservationsReply) GetReservations() []*Reservation {
	if x != nil {
		return x.Reservations
	}
	return nil
}

type ReservationInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampusType    room.CampusType        `protobuf:"varint,1,opt,name=campus_type,json=campusType,proto3,enum=room.v1.CampusType" json:"campus_type,omitempty"`
	Date          *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	FromHour      int32                  `protobuf:"varint,3,opt,name=from_hour,json=fromHour,proto3" json:"from_hour,omitempty"`
	FromMinute    int32                  `protobuf:"varint,4,opt,name=from_minute,json=fromMinute,proto3" json:"from_minute,omitempty"`
	ToHour        int32                  `protobuf:"varint,5,opt,name=to_hour,json=toHour,proto3" json:"to_hour,omitempty"`
	ToMinute      int32                  `protobuf:"varint,6,opt,name=to_minute,json=toMinute,proto3" json:"to_minute,omitempty"`
	IsAutoSelect  bool                   `protobuf:"varint,7,opt,name=is_auto_select,json=isAutoSelect,proto3" json:"is_auto_select,omitempty"`
	RoomId        *string                `protobuf:"bytes,8,opt,name=room_id,json=roomId,proto3,oneof" json:"room_id,omitempty"`
	BookerName    *string                `protobuf:"bytes,9,opt,name=booker_name,json=bookerName,proto3,oneof" json:"booker_name,omitempty"`
	PianoNumbers  []int32                `protobuf:"varint,10,rep,packed,name=piano_numbers,json=pianoNumbers,proto3" json:"piano_numbers,omitempty"`
	PianoTypes    []room.PianoType       `protobuf:"varint,11,rep,packed,name=piano_types,json=pianoTypes,proto3,enum=room.v1.PianoType" json:"piano_types,omitempty"`
	Floors        []int32                `protobuf:"varint,12,rep,packed,name=floors,proto3" json:"floors,omitempty"`
	IsBasement    *bool                  `protobuf:"varint,13,opt,name=is_basement,json=isBasement,proto3,oneof" json:"is_basement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservationInput) Reset() {
	*x = ReservationInput{}
	mi := &file_v1_reservation_reservation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservationInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationInput) ProtoMessage() {}

func (x *ReservationInput) ProtoReflect() protoreflect.Message {
	mi := &file_v1_reservation_reservation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservationInput.ProtoReflect.Descriptor instead.
func (*ReservationInput) Descriptor() ([]byte, []int) {
	return file_v1_reservation_reservation_proto_rawDescGZIP(), []int{5}
}

func (x *ReservationInput) GetCampusType() room.CampusType {
	if x != nil {
		return x.CampusType
	}
	return room.CampusType(0)
}

func (x *ReservationInput) GetDate() *timestamp.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *ReservationInput) GetFromHour() int32 {
	if x != nil {
		return x.FromHour
	}
	return 0
}

func (x *ReservationInput) GetFromMinute() int32 {
	if x != nil {
		return x.FromMinute
	}
	return 0
}

func (x *ReservationInput) GetToHour() int32 {
	if x != nil {
		return x.ToHour
	}
	return 0
}

func (x *ReservationInput) GetToMinute() int32 {
	if x != nil {
		return x.ToMinute
	}
	return 0
}

func (x *ReservationInput) GetIsAutoSelect() bool {
	if x != nil {
		return x.IsAutoSelect
	}
	return false
}

func (x *ReservationInput) GetRoomId() string {
	if x != nil && x.RoomId != nil {
		return *x.RoomId
	}
	return ""
}

func (x *ReservationInput) GetBookerName() string {
	if x != nil && x.BookerName != nil {
		return *x.BookerName
	}
	return ""
}

func (x *ReservationInput) GetPianoNumbers() []int32 {
	if x != nil {
		return x.PianoNumbers
	}
	return nil
}

func (x *ReservationInput) GetPianoTypes() []room.PianoType {
	if x != nil {
		return x.PianoTypes
	}
	return nil
}

func (x *ReservationInput) GetFloors() []int32 {
	if x != nil {
		return x.Floors
	}
	return nil
}

func (x *ReservationInput) GetIsBasement() bool {
	if x != nil && x.IsBasement != nil {
		return *x.IsBasement
	}
	return false
}

type CreateReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservation   *ReservationInput      `protobuf:"bytes,1,opt,name=reservation,proto3" json:"reservation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReservationRequest) Reset() {
	*x = CreateReservationRequest{}
	mi := &file_v1_reservation_reservation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReservationRequest) ProtoMessage() {}

func (x *CreateReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_reservation_reservation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReservationRequest.ProtoReflect.Descriptor instead.
func (*CreateReservationRequest) Descriptor() ([]byte, []int) {
	return file_v1_reservation_reservation_proto_rawDescGZIP(), []int{6}
}

func (x *CreateReservationRequest) GetReservation() *ReservationInput {
	if x != nil {
		return x.Reservation
	}
	return nil
}

type CreateReservationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservations  []*Reservation         `protobuf:"bytes,1,rep,name=reservations,proto3" json:"reservations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReservationReply) Reset() {
	*x = CreateReservationReply{}
	mi := &file_v1_reservation_reservation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReservationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReservationReply) ProtoMessage() {}

func (x *CreateReservationReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_reservation_reservation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReservationReply.ProtoReflect.Descriptor instead.
func (*CreateReservationReply) Descriptor() ([]byte, []int) {
	return file_v1_reservation_reservation_proto_rawDescGZIP(), []int{7}
}

func (x *CreateReservationReply) GetReservations() []*Reservation {
	if x != nil {
		return x.Reservations
	}
	return nil
}

type UpdateReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId int64                  `protobuf:"varint,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Reservation   *ReservationInput      `protobuf:"bytes,2,opt,name=reservation,proto3" json:"reservation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReservationRequest) Reset() {
	*x = UpdateReservationRequest{}
	mi := &file_v1_reservation_reservation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReservationRequest) ProtoMessage() {}

func (x *UpdateReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_reservation_reservation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReservationRequest.ProtoReflect.Descriptor instead.
func (*UpdateReservationRequest) Descriptor() ([]byte, []int) {
	return file_v1_reservation_reservation_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateReservationRequest) GetReservationId() int64 {
	if x != nil {
		return x.ReservationId
	}
	return 0
}

func (x *UpdateReservationRequest) GetReservation() *ReservationInput {
	if x != nil {
		return x.Reservation
	}
	return nil
}

type UpdateReservationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservation   *Reservation           `protobuf:"bytes,1,opt,name=reservation,proto3" json:"reservation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReservationReply) Reset() {
	*x = UpdateReservationReply{}
	mi := &file_v1_reservation_reservation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReservationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReservationReply) ProtoMessage() {}

func (x *UpdateReservationReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_reservation_reservation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReservationReply.ProtoReflect.Descriptor instead.
func (*UpdateReservationReply) Descriptor() ([]byte, []int) {
	return file_v1_reservation_reservation_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateReservationReply) GetReservation() *Reservation {
	if x != nil {
		return x.Reservation
	}
	return nil
}

type DeleteReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId int64                  `protobuf:"varint,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReservationRequest) Reset() {
	*x = DeleteReservationRequest{}
	mi := &file_v1_reservation_reservation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReservationRequest) ProtoMessage() {}

func (x *DeleteReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_reservation_reservation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReservationRequest.ProtoReflect.Descriptor instead.
func (*DeleteReservationRequest) Descriptor() ([]byte, []int) {
	return file_v1_reservation_reservation_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteReservationRequest) GetReservationId() int64 {
	if x != nil {
		return x.ReservationId
	}
	return 0
}

type DeleteReservationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReservationReply) Reset() {
	*x = DeleteReservationReply{}
	mi := &file_v1_reservation_reservation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReservationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReservationReply) ProtoMessage() {}

func (x *DeleteReservationReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_reservation_reservation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReservationReply.ProtoReflect.Descriptor instead.
func (*DeleteReservationReply) Descriptor() ([]byte, []int) {
	return file_v1_reservation_reservation_proto_rawDescGZIP(), []int{11}
}

var File_v1_reservation_reservation_proto protoreflect.FileDescriptor

const file_v1_reservation_reservation_proto_rawDesc = "" +
	"\n" +
	" v1/reservation/reservation.proto\x12\x0ereservation.v1\x1a\x12v1/room/room.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb7\x03\n" +
	"\vReservation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12$\n" +
	"\vexternal_id\x18\x02 \x01(\tH\x00R\n" +
	"externalId\x88\x01\x01\x124\n" +
	"\vcampus_type\x18\x03 \x01(\x0e2\x13.room.v1.CampusTypeR\n" +
	"campusType\x12.\n" +
	"\x04date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x17\n" +
	"\aroom_id\x18\x05 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tfrom_hour\x18\x06 \x01(\x05R\bfromHour\x12\x1f\n" +
	"\vfrom_minute\x18\a \x01(\x05R\n" +
	"fromMinute\x12\x17\n" +
	"\ato_hour\x18\b \x01(\x05R\x06toHour\x12\x1b\n" +
	"\tto_minute\x18\t \x01(\x05R\btoMinute\x12$\n" +
	"\vbooker_name\x18\n" +
	" \x01(\tH\x01R\n" +
	"bookerName\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x0e\n" +
	"\f_external_idB\x0e\n" +
	"\f_booker_name\">\n" +
	"\x15GetReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\x03R\rreservationId\"T\n" +
	"\x13GetReservationReply\x12=\n" +
	"\vreservation\x18\x01 \x01(\v2\x1b.reservation.v1.ReservationR\vreservation\"\x1c\n" +
	"\x1aGetUserReservationsRequest\"[\n" +
	"\x18GetUserReservationsReply\x12?\n" +
	"\freservations\x18\x01 \x03(\v2\x1b.reservation.v1.ReservationR\freservations\"\x9a\x04\n" +
	"\x10ReservationInput\x124\n" +
	"\vcampus_type\x18\x01 \x01(\x0e2\x13.room.v1.CampusTypeR\n" +
	"campusType\x12.\n" +
	"\x04date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x1b\n" +
	"\tfrom_hour\x18\x03 \x01(\x05R\bfromHour\x12\x1f\n" +
	"\vfrom_minute\x18\x04 \x01(\x05R\n" +
	"fromMinute\x12\x17\n" +
	"\ato_hour\x18\x05 \x01(\x05R\x06toHour\x12\x1b\n" +
	"\tto_minute\x18\x06 \x01(\x05R\btoMinute\x12$\n" +
	"\x0eis_auto_select\x18\a \x01(\bR\fisAutoSelect\x12\x1c\n" +
	"\aroom_id\x18\b \x01(\tH\x00R\x06roomId\x88\x01\x01\x12$\n" +
	"\vbooker_name\x18\t \x01(\tH\x01R\n" +
	"bookerName\x88\x01\x01\x12#\n" +
	"\rpiano_numbers\x18\n" +
	" \x03(\x05R\fpianoNumbers\x123\n" +
	"\vpiano_types\x18\v \x03(\x0e2\x12.room.v1.PianoTypeR\n" +
	"pianoTypes\x12\x16\n" +
	"\x06floors\x18\f \x03(\x05R\x06floors\x12$\n" +
	"\vis_basement\x18\r \x01(\bH\x02R\n" +
	"isBasement\x88\x01\x01B\n" +
	"\n" +
	"\b_room_idB\x0e\n" +
	"\f_booker_nameB\x0e\n" +
	"\f_is_basement\"^\n" +
	"\x18CreateReservationRequest\x12B\n" +
	"\vreservation\x18\x01 \x01(\v2 .reservation.v1.ReservationInputR\vreservation\"Y\n" +
	"\x16CreateReservationReply\x12?\n" +
	"\freservations\x18\x01 \x03(\v2\x1b.reservation.v1.ReservationR\freservations\"\x85\x01\n" +
	"\x18UpdateReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\x03R\rreservationId\x12B\n" +
	"\vreservation\x18\x02 \x01(\v2 .reservation.v1.ReservationInputR\vreservation\"W\n" +
	"\x16UpdateReservationReply\x12=\n" +
	"\vreservation\x18\x01 \x01(\v2\x1b.reservation.v1.ReservationR\vreservation\"A\n" +
	"\x18DeleteReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\x03R\rreservationId\"\x18\n" +
	"\x16DeleteReservationReply2\x92\x04\n" +
	"\x12ReservationService\x12\\\n" +
	"\x0eGetReservation\x12%.reservation.v1.GetReservationRequest\x1a#.reservation.v1.GetReservationReply\x12i\n" +
	"\x11GetMyReservations\x12*.reservation.v1.GetUserReservationsRequest\x1a(.reservation.v1.GetUserReservationsReply\x12e\n" +
	"\x11CreateReservation\x12(.reservation.v1.CreateReservationRequest\x1a&.reservation.v1.CreateReservationReply\x12e\n" +
	"\x11UpdateReservation\x12(.reservation.v1.UpdateReservationRequest\x1a&.reservation.v1.UpdateReservationReply\x12e\n" +
	"\x11DeleteReservation\x12(.reservation.v1.DeleteReservationRequest\x1a&.reservation.v1.DeleteReservationReplyBFZDgithub.com/ekkx/tcmrsv-web/server/internal/shared/api/v1/reservationb\x06proto3"

var (
	file_v1_reservation_reservation_proto_rawDescOnce sync.Once
	file_v1_reservation_reservation_proto_rawDescData []byte
)

func file_v1_reservation_reservation_proto_rawDescGZIP() []byte {
	file_v1_reservation_reservation_proto_rawDescOnce.Do(func() {
		file_v1_reservation_reservation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_reservation_reservation_proto_rawDesc), len(file_v1_reservation_reservation_proto_rawDesc)))
	})
	return file_v1_reservation_reservation_proto_rawDescData
}

var file_v1_reservation_reservation_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_v1_reservation_reservation_proto_goTypes = []any{
	(*Reservation)(nil),                // 0: reservation.v1.Reservation
	(*GetReservationRequest)(nil),      // 1: reservation.v1.GetReservationRequest
	(*GetReservationReply)(nil),        // 2: reservation.v1.GetReservationReply
	(*GetUserReservationsRequest)(nil), // 3: reservation.v1.GetUserReservationsRequest
	(*GetUserReservationsReply)(nil),   // 4: reservation.v1.GetUserReservationsReply
	(*ReservationInput)(nil),           // 5: reservation.v1.ReservationInput
	(*CreateReservationRequest)(nil),   // 6: reservation.v1.CreateReservationRequest
	(*CreateReservationReply)(nil),     // 7: reservation.v1.CreateReservationReply
	(*UpdateReservationRequest)(nil),   // 8: reservation.v1.UpdateReservationRequest
	(*UpdateReservationReply)(nil),     // 9: reservation.v1.UpdateReservationReply
	(*DeleteReservationRequest)(nil),   // 10: reservation.v1.DeleteReservationRequest
	(*DeleteReservationReply)(nil),     // 11: reservation.v1.DeleteReservationReply
	(room.CampusType)(0),               // 12: room.v1.CampusType
	(*timestamp.Timestamp)(nil),        // 13: google.protobuf.Timestamp
	(room.PianoType)(0),                // 14: room.v1.PianoType
}
var file_v1_reservation_reservation_proto_depIdxs = []int32{
	12, // 0: reservation.v1.Reservation.campus_type:type_name -> room.v1.CampusType
	13, // 1: reservation.v1.Reservation.date:type_name -> google.protobuf.Timestamp
	13, // 2: reservation.v1.Reservation.created_at:type_name -> google.protobuf.Timestamp
	0,  // 3: reservation.v1.GetReservationReply.reservation:type_name -> reservation.v1.Reservation
	0,  // 4: reservation.v1.GetUserReservationsReply.reservations:type_name -> reservation.v1.Reservation
	12, // 5: reservation.v1.ReservationInput.campus_type:type_name -> room.v1.CampusType
	13, // 6: reservation.v1.ReservationInput.date:type_name -> google.protobuf.Timestamp
	14, // 7: reservation.v1.ReservationInput.piano_types:type_name -> room.v1.PianoType
	5,  // 8: reservation.v1.CreateReservationRequest.reservation:type_name -> reservation.v1.ReservationInput
	0,  // 9: reservation.v1.CreateReservationReply.reservations:type_name -> reservation.v1.Reservation
	5,  // 10: reservation.v1.UpdateReservationRequest.reservation:type_name -> reservation.v1.ReservationInput
	0,  // 11: reservation.v1.UpdateReservationReply.reservation:type_name -> reservation.v1.Reservation
	1,  // 12: reservation.v1.ReservationService.GetReservation:input_type -> reservation.v1.GetReservationRequest
	3,  // 13: reservation.v1.ReservationService.GetMyReservations:input_type -> reservation.v1.GetUserReservationsRequest
	6,  // 14: reservation.v1.ReservationService.CreateReservation:input_type -> reservation.v1.CreateReservationRequest
	8,  // 15: reservation.v1.ReservationService.UpdateReservation:input_type -> reservation.v1.UpdateReservationRequest
	10, // 16: reservation.v1.ReservationService.DeleteReservation:input_type -> reservation.v1.DeleteReservationRequest
	2,  // 17: reservation.v1.ReservationService.GetReservation:output_type -> reservation.v1.GetReservationReply
	4,  // 18: reservation.v1.ReservationService.GetMyReservations:output_type -> reservation.v1.GetUserReservationsReply
	7,  // 19: reservation.v1.ReservationService.CreateReservation:output_type -> reservation.v1.CreateReservationReply
	9,  // 20: reservation.v1.ReservationService.UpdateReservation:output_type -> reservation.v1.UpdateReservationReply
	11, // 21: reservation.v1.ReservationService.DeleteReservation:output_type -> reservation.v1.DeleteReservationReply
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_v1_reservation_reservation_proto_init() }
func file_v1_reservation_reservation_proto_init() {
	if File_v1_reservation_reservation_proto != nil {
		return
	}
	file_v1_reservation_reservation_proto_msgTypes[0].OneofWrappers = []any{}
	file_v1_reservation_reservation_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_reservation_reservation_proto_rawDesc), len(file_v1_reservation_reservation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_reservation_reservation_proto_goTypes,
		DependencyIndexes: file_v1_reservation_reservation_proto_depIdxs,
		MessageInfos:      file_v1_reservation_reservation_proto_msgTypes,
	}.Build()
	File_v1_reservation_reservation_proto = out.File
	file_v1_reservation_reservation_proto_goTypes = nil
	file_v1_reservation_reservation_proto_depIdxs = nil
}
