// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: create_user.sql

package database

import (
	"context"

	"github.com/ekkx/tcmrsv-web/server/pkg/ulid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO
    users (
        id,
        display_name,
        master_user_id,
        encrypted_password,
        create_time,
        update_time
    )
VALUES
    (
        $1::ulid,
        $2::TEXT,
        $3::ulid,
        $4::TEXT,
        NOW(),
        NOW()
    )
RETURNING users.id
`

type CreateUserParams struct {
	ID                ulid.ULID  `json:"id"`
	DisplayName       string     `json:"display_name"`
	MasterUserID      *ulid.ULID `json:"master_user_id"`
	EncryptedPassword string     `json:"encrypted_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (ulid.ULID, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.DisplayName,
		arg.MasterUserID,
		arg.EncryptedPassword,
	)
	var id ulid.ULID
	err := row.Scan(&id)
	return id, err
}
