// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_user_meta_by_id.sql

package database

import (
	"context"

	"github.com/ekkx/tcmrsv-web/server/pkg/ulid"
)

const getUserMetaByID = `-- name: GetUserMetaByID :one
SELECT
    users.id AS user_id,
    users.master_user_id AS master_user_id
FROM
    users
WHERE
    users.id = $1::ulid
`

type GetUserMetaByIDRow struct {
	UserID       ulid.ULID  `json:"user_id"`
	MasterUserID *ulid.ULID `json:"master_user_id"`
}

func (q *Queries) GetUserMetaByID(ctx context.Context, userID ulid.ULID) (GetUserMetaByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserMetaByID, userID)
	var i GetUserMetaByIDRow
	err := row.Scan(&i.UserID, &i.MasterUserID)
	return i, err
}
