// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: list_users_by_ids.sql

package database

import (
	"context"
)

const listUsersByIDs = `-- name: ListUsersByIDs :many
SELECT
    users.id, users.password, users.official_site_id, users.official_site_password, users.master_user_id, users.display_name, users.create_time
FROM
    users
WHERE
    users.id = ANY($1::TEXT[])
`

func (q *Queries) ListUsersByIDs(ctx context.Context, userIds []string) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByIDs, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Password,
			&i.OfficialSiteID,
			&i.OfficialSitePassword,
			&i.MasterUserID,
			&i.DisplayName,
			&i.CreateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
