// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: list_slave_user_ids.sql

package database

import (
	"context"

	"github.com/ekkx/tcmrsv-web/server/pkg/ulid"
)

const listSlaveUserIDs = `-- name: ListSlaveUserIDs :many
SELECT
    users.id as user_id
FROM
    users
WHERE
    users.master_user_id = $1::ulid
ORDER BY
    users.id DESC
`

func (q *Queries) ListSlaveUserIDs(ctx context.Context, masterUserID ulid.ULID) ([]ulid.ULID, error) {
	rows, err := q.db.Query(ctx, listSlaveUserIDs, masterUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ulid.ULID{}
	for rows.Next() {
		var user_id ulid.ULID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
