// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"

	"github.com/ekkx/tcmrsv-web/server/pkg/ulid"
)

type Querier interface {
	CreateReservation(ctx context.Context, arg CreateReservationParams) (ulid.ULID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (ulid.ULID, error)
	DeleteUserByID(ctx context.Context, userID ulid.ULID) (int32, error)
	GetUserIDByOfficialSiteID(ctx context.Context, officialSiteID string) (ulid.ULID, error)
	IsReservationConflicted(ctx context.Context, arg IsReservationConflictedParams) (bool, error)
	ListReservationsByIDs(ctx context.Context, reservationIds []string) ([]Reservation, error)
	ListSlaveUsersMeta(ctx context.Context, arg ListSlaveUsersMetaParams) ([]ListSlaveUsersMetaRow, error)
	ListUnavailableRoomIDs(ctx context.Context, arg ListUnavailableRoomIDsParams) ([]string, error)
	ListUserReservationIDs(ctx context.Context, arg ListUserReservationIDsParams) ([]ulid.ULID, error)
	ListUsersByIDs(ctx context.Context, userIds []string) ([]User, error)
	UpdateUserByID(ctx context.Context, arg UpdateUserByIDParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
