// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: room/v1/room.proto

package roomv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CampusType int32

const (
	CampusType_CAMPUS_TYPE_UNSPECIFIED CampusType = 0
	CampusType_CAMPUS_TYPE_NAKAMEGURO  CampusType = 1
	CampusType_CAMPUS_TYPE_IKEBUKURO   CampusType = 2
)

// Enum value maps for CampusType.
var (
	CampusType_name = map[int32]string{
		0: "CAMPUS_TYPE_UNSPECIFIED",
		1: "CAMPUS_TYPE_NAKAMEGURO",
		2: "CAMPUS_TYPE_IKEBUKURO",
	}
	CampusType_value = map[string]int32{
		"CAMPUS_TYPE_UNSPECIFIED": 0,
		"CAMPUS_TYPE_NAKAMEGURO":  1,
		"CAMPUS_TYPE_IKEBUKURO":   2,
	}
)

func (x CampusType) Enum() *CampusType {
	p := new(CampusType)
	*p = x
	return p
}

func (x CampusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CampusType) Descriptor() protoreflect.EnumDescriptor {
	return file_room_v1_room_proto_enumTypes[0].Descriptor()
}

func (CampusType) Type() protoreflect.EnumType {
	return &file_room_v1_room_proto_enumTypes[0]
}

func (x CampusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CampusType.Descriptor instead.
func (CampusType) EnumDescriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{0}
}

type PianoType int32

const (
	PianoType_PIANO_TYPE_UNSPECIFIED PianoType = 0
	PianoType_PIANO_TYPE_GRAND       PianoType = 1
	PianoType_PIANO_TYPE_UPRIGHT     PianoType = 2
	PianoType_PIANO_TYPE_NONE        PianoType = 3
)

// Enum value maps for PianoType.
var (
	PianoType_name = map[int32]string{
		0: "PIANO_TYPE_UNSPECIFIED",
		1: "PIANO_TYPE_GRAND",
		2: "PIANO_TYPE_UPRIGHT",
		3: "PIANO_TYPE_NONE",
	}
	PianoType_value = map[string]int32{
		"PIANO_TYPE_UNSPECIFIED": 0,
		"PIANO_TYPE_GRAND":       1,
		"PIANO_TYPE_UPRIGHT":     2,
		"PIANO_TYPE_NONE":        3,
	}
)

func (x PianoType) Enum() *PianoType {
	p := new(PianoType)
	*p = x
	return p
}

func (x PianoType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PianoType) Descriptor() protoreflect.EnumDescriptor {
	return file_room_v1_room_proto_enumTypes[1].Descriptor()
}

func (PianoType) Type() protoreflect.EnumType {
	return &file_room_v1_room_proto_enumTypes[1]
}

func (x PianoType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PianoType.Descriptor instead.
func (PianoType) EnumDescriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{1}
}

type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PianoType     PianoType              `protobuf:"varint,3,opt,name=piano_type,json=pianoType,proto3,enum=room.v1.PianoType" json:"piano_type,omitempty"`
	PianoCount    int32                  `protobuf:"varint,4,opt,name=piano_count,json=pianoCount,proto3" json:"piano_count,omitempty"`
	IsClassroom   bool                   `protobuf:"varint,5,opt,name=is_classroom,json=isClassroom,proto3" json:"is_classroom,omitempty"`
	IsBasement    bool                   `protobuf:"varint,6,opt,name=is_basement,json=isBasement,proto3" json:"is_basement,omitempty"`
	CampusType    CampusType             `protobuf:"varint,7,opt,name=campus_type,json=campusType,proto3,enum=room.v1.CampusType" json:"campus_type,omitempty"`
	Floor         int32                  `protobuf:"varint,8,opt,name=floor,proto3" json:"floor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_room_v1_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{0}
}

func (x *Room) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Room) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Room) GetPianoType() PianoType {
	if x != nil {
		return x.PianoType
	}
	return PianoType_PIANO_TYPE_UNSPECIFIED
}

func (x *Room) GetPianoCount() int32 {
	if x != nil {
		return x.PianoCount
	}
	return 0
}

func (x *Room) GetIsClassroom() bool {
	if x != nil {
		return x.IsClassroom
	}
	return false
}

func (x *Room) GetIsBasement() bool {
	if x != nil {
		return x.IsBasement
	}
	return false
}

func (x *Room) GetCampusType() CampusType {
	if x != nil {
		return x.CampusType
	}
	return CampusType_CAMPUS_TYPE_UNSPECIFIED
}

func (x *Room) GetFloor() int32 {
	if x != nil {
		return x.Floor
	}
	return 0
}

type ListAvailableRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampusType    CampusType             `protobuf:"varint,1,opt,name=campus_type,json=campusType,proto3,enum=room.v1.CampusType" json:"campus_type,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	FromHour      int32                  `protobuf:"varint,3,opt,name=from_hour,json=fromHour,proto3" json:"from_hour,omitempty"`
	FromMinute    int32                  `protobuf:"varint,4,opt,name=from_minute,json=fromMinute,proto3" json:"from_minute,omitempty"`
	ToHour        int32                  `protobuf:"varint,5,opt,name=to_hour,json=toHour,proto3" json:"to_hour,omitempty"`
	ToMinute      int32                  `protobuf:"varint,6,opt,name=to_minute,json=toMinute,proto3" json:"to_minute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAvailableRoomsRequest) Reset() {
	*x = ListAvailableRoomsRequest{}
	mi := &file_room_v1_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAvailableRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailableRoomsRequest) ProtoMessage() {}

func (x *ListAvailableRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailableRoomsRequest.ProtoReflect.Descriptor instead.
func (*ListAvailableRoomsRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{1}
}

func (x *ListAvailableRoomsRequest) GetCampusType() CampusType {
	if x != nil {
		return x.CampusType
	}
	return CampusType_CAMPUS_TYPE_UNSPECIFIED
}

func (x *ListAvailableRoomsRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ListAvailableRoomsRequest) GetFromHour() int32 {
	if x != nil {
		return x.FromHour
	}
	return 0
}

func (x *ListAvailableRoomsRequest) GetFromMinute() int32 {
	if x != nil {
		return x.FromMinute
	}
	return 0
}

func (x *ListAvailableRoomsRequest) GetToHour() int32 {
	if x != nil {
		return x.ToHour
	}
	return 0
}

func (x *ListAvailableRoomsRequest) GetToMinute() int32 {
	if x != nil {
		return x.ToMinute
	}
	return 0
}

type ListAvailableRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*Room                `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAvailableRoomsResponse) Reset() {
	*x = ListAvailableRoomsResponse{}
	mi := &file_room_v1_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAvailableRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailableRoomsResponse) ProtoMessage() {}

func (x *ListAvailableRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailableRoomsResponse.ProtoReflect.Descriptor instead.
func (*ListAvailableRoomsResponse) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{2}
}

func (x *ListAvailableRoomsResponse) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

var File_room_v1_room_proto protoreflect.FileDescriptor

const file_room_v1_room_proto_rawDesc = "" +
	"\n" +
	"\x12room/v1/room.proto\x12\aroom.v1\"\x8e\x02\n" +
	"\x04Room\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x121\n" +
	"\n" +
	"piano_type\x18\x03 \x01(\x0e2\x12.room.v1.PianoTypeR\tpianoType\x12\x1f\n" +
	"\vpiano_count\x18\x04 \x01(\x05R\n" +
	"pianoCount\x12!\n" +
	"\fis_classroom\x18\x05 \x01(\bR\visClassroom\x12\x1f\n" +
	"\vis_basement\x18\x06 \x01(\bR\n" +
	"isBasement\x124\n" +
	"\vcampus_type\x18\a \x01(\x0e2\x13.room.v1.CampusTypeR\n" +
	"campusType\x12\x14\n" +
	"\x05floor\x18\b \x01(\x05R\x05floor\"\xd9\x01\n" +
	"\x19ListAvailableRoomsRequest\x124\n" +
	"\vcampus_type\x18\x01 \x01(\x0e2\x13.room.v1.CampusTypeR\n" +
	"campusType\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x1b\n" +
	"\tfrom_hour\x18\x03 \x01(\x05R\bfromHour\x12\x1f\n" +
	"\vfrom_minute\x18\x04 \x01(\x05R\n" +
	"fromMinute\x12\x17\n" +
	"\ato_hour\x18\x05 \x01(\x05R\x06toHour\x12\x1b\n" +
	"\tto_minute\x18\x06 \x01(\x05R\btoMinute\"A\n" +
	"\x1aListAvailableRoomsResponse\x12#\n" +
	"\x05rooms\x18\x01 \x03(\v2\r.room.v1.RoomR\x05rooms*`\n" +
	"\n" +
	"CampusType\x12\x1b\n" +
	"\x17CAMPUS_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CAMPUS_TYPE_NAKAMEGURO\x10\x01\x12\x19\n" +
	"\x15CAMPUS_TYPE_IKEBUKURO\x10\x02*j\n" +
	"\tPianoType\x12\x1a\n" +
	"\x16PIANO_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10PIANO_TYPE_GRAND\x10\x01\x12\x16\n" +
	"\x12PIANO_TYPE_UPRIGHT\x10\x02\x12\x13\n" +
	"\x0fPIANO_TYPE_NONE\x10\x032l\n" +
	"\vRoomService\x12]\n" +
	"\x12ListAvailableRooms\x12\".room.v1.ListAvailableRoomsRequest\x1a#.room.v1.ListAvailableRoomsResponseB\x93\x01\n" +
	"\vcom.room.v1B\tRoomProtoP\x01Z<github.com/ekkx/tcmrsv-web/internal/shared/pb/room/v1;roomv1\xa2\x02\x03RXX\xaa\x02\aRoom.V1\xca\x02\aRoom\\V1\xe2\x02\x13Room\\V1\\GPBMetadata\xea\x02\bRoom::V1b\x06proto3"

var (
	file_room_v1_room_proto_rawDescOnce sync.Once
	file_room_v1_room_proto_rawDescData []byte
)

func file_room_v1_room_proto_rawDescGZIP() []byte {
	file_room_v1_room_proto_rawDescOnce.Do(func() {
		file_room_v1_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_room_v1_room_proto_rawDesc), len(file_room_v1_room_proto_rawDesc)))
	})
	return file_room_v1_room_proto_rawDescData
}

var file_room_v1_room_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_room_v1_room_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_room_v1_room_proto_goTypes = []any{
	(CampusType)(0),                    // 0: room.v1.CampusType
	(PianoType)(0),                     // 1: room.v1.PianoType
	(*Room)(nil),                       // 2: room.v1.Room
	(*ListAvailableRoomsRequest)(nil),  // 3: room.v1.ListAvailableRoomsRequest
	(*ListAvailableRoomsResponse)(nil), // 4: room.v1.ListAvailableRoomsResponse
}
var file_room_v1_room_proto_depIdxs = []int32{
	1, // 0: room.v1.Room.piano_type:type_name -> room.v1.PianoType
	0, // 1: room.v1.Room.campus_type:type_name -> room.v1.CampusType
	0, // 2: room.v1.ListAvailableRoomsRequest.campus_type:type_name -> room.v1.CampusType
	2, // 3: room.v1.ListAvailableRoomsResponse.rooms:type_name -> room.v1.Room
	3, // 4: room.v1.RoomService.ListAvailableRooms:input_type -> room.v1.ListAvailableRoomsRequest
	4, // 5: room.v1.RoomService.ListAvailableRooms:output_type -> room.v1.ListAvailableRoomsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_room_v1_room_proto_init() }
func file_room_v1_room_proto_init() {
	if File_room_v1_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_room_v1_room_proto_rawDesc), len(file_room_v1_room_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_room_v1_room_proto_goTypes,
		DependencyIndexes: file_room_v1_room_proto_depIdxs,
		EnumInfos:         file_room_v1_room_proto_enumTypes,
		MessageInfos:      file_room_v1_room_proto_msgTypes,
	}.Build()
	File_room_v1_room_proto = out.File
	file_room_v1_room_proto_goTypes = nil
	file_room_v1_room_proto_depIdxs = nil
}
