// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerScopes = "bearer.Scopes"
)

// Defines values for ReservationCampusCode.
const (
	ReservationCampusCodeN1 ReservationCampusCode = "1"
	ReservationCampusCodeN2 ReservationCampusCode = "2"
)

// Defines values for CreateReservationJSONBodyCampusCode.
const (
	CreateReservationJSONBodyCampusCodeN1 CreateReservationJSONBodyCampusCode = 1
	CreateReservationJSONBodyCampusCodeN2 CreateReservationJSONBodyCampusCode = 2
)

// Defines values for CreateReservationJSONBodyPianoTypes.
const (
	CreateReservationJSONBodyPianoTypesGrand   CreateReservationJSONBodyPianoTypes = "grand"
	CreateReservationJSONBodyPianoTypesNone    CreateReservationJSONBodyPianoTypes = "none"
	CreateReservationJSONBodyPianoTypesUpright CreateReservationJSONBodyPianoTypes = "upright"
)

// Defines values for UpdateReservationJSONBodyCampusCode.
const (
	UpdateReservationJSONBodyCampusCodeN1 UpdateReservationJSONBodyCampusCode = 1
	UpdateReservationJSONBodyCampusCodeN2 UpdateReservationJSONBodyCampusCode = 2
)

// Defines values for UpdateReservationJSONBodyPianoTypes.
const (
	UpdateReservationJSONBodyPianoTypesGrand   UpdateReservationJSONBodyPianoTypes = "grand"
	UpdateReservationJSONBodyPianoTypesNone    UpdateReservationJSONBodyPianoTypes = "none"
	UpdateReservationJSONBodyPianoTypesUpright UpdateReservationJSONBodyPianoTypes = "upright"
)

// Defines values for GetRoomsParamsPianoType.
const (
	Grand   GetRoomsParamsPianoType = "grand"
	None    GetRoomsParamsPianoType = "none"
	Upright GetRoomsParamsPianoType = "upright"
)

// Defines values for GetRoomsParamsCampusCode.
const (
	GetRoomsParamsCampusCodeN1 GetRoomsParamsCampusCode = 1
	GetRoomsParamsCampusCodeN2 GetRoomsParamsCampusCode = 2
)

// Authorization defines model for Authorization.
type Authorization struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

// Reservation defines model for Reservation.
type Reservation struct {
	CampusCode ReservationCampusCode `json:"campus_code"`
	Date       time.Time             `json:"date"`
	FromHour   int                   `json:"fromHour"`
	FromMinute int                   `json:"fromMinute"`
	Id         string                `json:"id"`
	RoomId     string                `json:"room_id"`
	ToHour     int                   `json:"toHour"`
	ToMinute   int                   `json:"toMinute"`
}

// ReservationCampusCode defines model for Reservation.CampusCode.
type ReservationCampusCode string

// ReservationList defines model for ReservationList.
type ReservationList struct {
	Reservations []Reservation `json:"reservations"`
}

// Response defines model for Response.
type Response struct {
	Code int                    `json:"code"`
	Data map[string]interface{} `json:"data"`
	Ok   bool                   `json:"ok"`
}

// Room defines model for Room.
type Room struct {
	CampusCode  int     `json:"campus_code"`
	Floor       float32 `json:"floor"`
	Id          string  `json:"id"`
	IsBasement  bool    `json:"is_basement"`
	IsClassroom bool    `json:"is_classroom"`
	Name        string  `json:"name"`
	PianoNumber int     `json:"piano_number"`
	PianoType   string  `json:"piano_type"`
}

// AuthorizeJSONBody defines parameters for Authorize.
type AuthorizeJSONBody struct {
	Password string `json:"password"`
	UserId   string `json:"user_id"`
}

// CreateReservationJSONBody defines parameters for CreateReservation.
type CreateReservationJSONBody struct {
	BookerName   *string                                `json:"booker_name,omitempty"`
	CampusCode   CreateReservationJSONBodyCampusCode    `json:"campus_code"`
	Date         time.Time                              `json:"date"`
	Floors       *[]int                                 `json:"floors,omitempty"`
	FromHour     int                                    `json:"from_hour"`
	FromMinute   string                                 `json:"from_minute"`
	IsAutoSelect bool                                   `json:"is_auto_select"`
	IsBasement   *bool                                  `json:"is_basement,omitempty"`
	PianoNumbers *[]int                                 `json:"piano_numbers,omitempty"`
	PianoTypes   *[]CreateReservationJSONBodyPianoTypes `json:"piano_types,omitempty"`
	RoomId       *string                                `json:"room_id,omitempty"`
	ToHour       string                                 `json:"to_hour"`
	ToMinute     string                                 `json:"to_minute"`
}

// CreateReservationJSONBodyCampusCode defines parameters for CreateReservation.
type CreateReservationJSONBodyCampusCode int

// CreateReservationJSONBodyPianoTypes defines parameters for CreateReservation.
type CreateReservationJSONBodyPianoTypes string

// UpdateReservationJSONBody defines parameters for UpdateReservation.
type UpdateReservationJSONBody struct {
	BookerName   *string                                `json:"booker_name,omitempty"`
	CampusCode   UpdateReservationJSONBodyCampusCode    `json:"campus_code"`
	Date         time.Time                              `json:"date"`
	Floors       *[]int                                 `json:"floors,omitempty"`
	FromHour     int                                    `json:"from_hour"`
	FromMinute   string                                 `json:"from_minute"`
	IsAutoSelect bool                                   `json:"is_auto_select"`
	IsBasement   *bool                                  `json:"is_basement,omitempty"`
	PianoNumbers *[]int                                 `json:"piano_numbers,omitempty"`
	PianoTypes   *[]UpdateReservationJSONBodyPianoTypes `json:"piano_types,omitempty"`
	RoomId       *string                                `json:"room_id,omitempty"`
	ToHour       string                                 `json:"to_hour"`
	ToMinute     string                                 `json:"to_minute"`
}

// UpdateReservationJSONBodyCampusCode defines parameters for UpdateReservation.
type UpdateReservationJSONBodyCampusCode int

// UpdateReservationJSONBodyPianoTypes defines parameters for UpdateReservation.
type UpdateReservationJSONBodyPianoTypes string

// GetRoomsParams defines parameters for GetRooms.
type GetRoomsParams struct {
	Id          *string                   `form:"id,omitempty" json:"id,omitempty"`
	Name        *string                   `form:"name,omitempty" json:"name,omitempty"`
	PianoNumber *int                      `form:"piano_number,omitempty" json:"piano_number,omitempty"`
	PianoType   *GetRoomsParamsPianoType  `form:"piano_type,omitempty" json:"piano_type,omitempty"`
	Floor       *int                      `form:"floor,omitempty" json:"floor,omitempty"`
	IsBasement  *bool                     `form:"is_basement,omitempty" json:"is_basement,omitempty"`
	CampusCode  *GetRoomsParamsCampusCode `form:"campus_code,omitempty" json:"campus_code,omitempty"`
}

// GetRoomsParamsPianoType defines parameters for GetRooms.
type GetRoomsParamsPianoType string

// GetRoomsParamsCampusCode defines parameters for GetRooms.
type GetRoomsParamsCampusCode int

// AuthorizeJSONRequestBody defines body for Authorize for application/json ContentType.
type AuthorizeJSONRequestBody AuthorizeJSONBody

// CreateReservationJSONRequestBody defines body for CreateReservation for application/json ContentType.
type CreateReservationJSONRequestBody CreateReservationJSONBody

// UpdateReservationJSONRequestBody defines body for UpdateReservation for application/json ContentType.
type UpdateReservationJSONRequestBody UpdateReservationJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// AuthorizeWithBody request with any body
	AuthorizeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	Authorize(ctx context.Context, body AuthorizeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateReservationWithBody request with any body
	CreateReservationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateReservation(ctx context.Context, body CreateReservationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMyReservations request
	GetMyReservations(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetReservation request
	GetReservation(ctx context.Context, reservationId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteReservation request
	DeleteReservation(ctx context.Context, reservationId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateReservationWithBody request with any body
	UpdateReservationWithBody(ctx context.Context, reservationId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateReservation(ctx context.Context, reservationId string, body UpdateReservationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetRooms request
	GetRooms(ctx context.Context, params *GetRoomsParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) AuthorizeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAuthorizeRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Authorize(ctx context.Context, body AuthorizeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAuthorizeRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateReservationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateReservationRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateReservation(ctx context.Context, body CreateReservationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateReservationRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetMyReservations(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMyReservationsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetReservation(ctx context.Context, reservationId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetReservationRequest(c.Server, reservationId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteReservation(ctx context.Context, reservationId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteReservationRequest(c.Server, reservationId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateReservationWithBody(ctx context.Context, reservationId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateReservationRequestWithBody(c.Server, reservationId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateReservation(ctx context.Context, reservationId string, body UpdateReservationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateReservationRequest(c.Server, reservationId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetRooms(ctx context.Context, params *GetRoomsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRoomsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewAuthorizeRequest calls the generic Authorize builder with application/json body
func NewAuthorizeRequest(server string, body AuthorizeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAuthorizeRequestWithBody(server, "application/json", bodyReader)
}

// NewAuthorizeRequestWithBody generates requests for Authorize with any type of body
func NewAuthorizeRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/authorize")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateReservationRequest calls the generic CreateReservation builder with application/json body
func NewCreateReservationRequest(server string, body CreateReservationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateReservationRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateReservationRequestWithBody generates requests for CreateReservation with any type of body
func NewCreateReservationRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/reservations/create")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetMyReservationsRequest generates requests for GetMyReservations
func NewGetMyReservationsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/reservations/mine")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetReservationRequest generates requests for GetReservation
func NewGetReservationRequest(server string, reservationId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "reservation_id", runtime.ParamLocationPath, reservationId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/reservations/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteReservationRequest generates requests for DeleteReservation
func NewDeleteReservationRequest(server string, reservationId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "reservation_id", runtime.ParamLocationPath, reservationId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/reservations/%s/delete", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateReservationRequest calls the generic UpdateReservation builder with application/json body
func NewUpdateReservationRequest(server string, reservationId string, body UpdateReservationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateReservationRequestWithBody(server, reservationId, "application/json", bodyReader)
}

// NewUpdateReservationRequestWithBody generates requests for UpdateReservation with any type of body
func NewUpdateReservationRequestWithBody(server string, reservationId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "reservation_id", runtime.ParamLocationPath, reservationId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/reservations/%s/update", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetRoomsRequest generates requests for GetRooms
func NewGetRoomsRequest(server string, params *GetRoomsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/rooms")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Id != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "id", runtime.ParamLocationQuery, *params.Id); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Name != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "name", runtime.ParamLocationQuery, *params.Name); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PianoNumber != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "piano_number", runtime.ParamLocationQuery, *params.PianoNumber); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PianoType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "piano_type", runtime.ParamLocationQuery, *params.PianoType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Floor != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "floor", runtime.ParamLocationQuery, *params.Floor); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.IsBasement != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "is_basement", runtime.ParamLocationQuery, *params.IsBasement); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.CampusCode != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "campus_code", runtime.ParamLocationQuery, *params.CampusCode); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// AuthorizeWithBodyWithResponse request with any body
	AuthorizeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AuthorizeResponse, error)

	AuthorizeWithResponse(ctx context.Context, body AuthorizeJSONRequestBody, reqEditors ...RequestEditorFn) (*AuthorizeResponse, error)

	// CreateReservationWithBodyWithResponse request with any body
	CreateReservationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateReservationResponse, error)

	CreateReservationWithResponse(ctx context.Context, body CreateReservationJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateReservationResponse, error)

	// GetMyReservationsWithResponse request
	GetMyReservationsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetMyReservationsResponse, error)

	// GetReservationWithResponse request
	GetReservationWithResponse(ctx context.Context, reservationId string, reqEditors ...RequestEditorFn) (*GetReservationResponse, error)

	// DeleteReservationWithResponse request
	DeleteReservationWithResponse(ctx context.Context, reservationId string, reqEditors ...RequestEditorFn) (*DeleteReservationResponse, error)

	// UpdateReservationWithBodyWithResponse request with any body
	UpdateReservationWithBodyWithResponse(ctx context.Context, reservationId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateReservationResponse, error)

	UpdateReservationWithResponse(ctx context.Context, reservationId string, body UpdateReservationJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateReservationResponse, error)

	// GetRoomsWithResponse request
	GetRoomsWithResponse(ctx context.Context, params *GetRoomsParams, reqEditors ...RequestEditorFn) (*GetRoomsResponse, error)
}

type AuthorizeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Code int           `json:"code"`
		Data Authorization `json:"data"`
		Ok   bool          `json:"ok"`
	}
}

// Status returns HTTPResponse.Status
func (r AuthorizeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AuthorizeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateReservationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Response
}

// Status returns HTTPResponse.Status
func (r CreateReservationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateReservationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetMyReservationsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Code int             `json:"code"`
		Data ReservationList `json:"data"`
		Ok   bool            `json:"ok"`
	}
}

// Status returns HTTPResponse.Status
func (r GetMyReservationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMyReservationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetReservationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Code int         `json:"code"`
		Data Reservation `json:"data"`
		Ok   bool        `json:"ok"`
	}
}

// Status returns HTTPResponse.Status
func (r GetReservationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetReservationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteReservationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Response
}

// Status returns HTTPResponse.Status
func (r DeleteReservationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteReservationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateReservationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Response
}

// Status returns HTTPResponse.Status
func (r UpdateReservationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateReservationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetRoomsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Code int `json:"code"`
		Data struct {
			Rooms []Room `json:"rooms"`
		} `json:"data"`
		Ok bool `json:"ok"`
	}
}

// Status returns HTTPResponse.Status
func (r GetRoomsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRoomsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// AuthorizeWithBodyWithResponse request with arbitrary body returning *AuthorizeResponse
func (c *ClientWithResponses) AuthorizeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AuthorizeResponse, error) {
	rsp, err := c.AuthorizeWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAuthorizeResponse(rsp)
}

func (c *ClientWithResponses) AuthorizeWithResponse(ctx context.Context, body AuthorizeJSONRequestBody, reqEditors ...RequestEditorFn) (*AuthorizeResponse, error) {
	rsp, err := c.Authorize(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAuthorizeResponse(rsp)
}

// CreateReservationWithBodyWithResponse request with arbitrary body returning *CreateReservationResponse
func (c *ClientWithResponses) CreateReservationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateReservationResponse, error) {
	rsp, err := c.CreateReservationWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateReservationResponse(rsp)
}

func (c *ClientWithResponses) CreateReservationWithResponse(ctx context.Context, body CreateReservationJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateReservationResponse, error) {
	rsp, err := c.CreateReservation(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateReservationResponse(rsp)
}

// GetMyReservationsWithResponse request returning *GetMyReservationsResponse
func (c *ClientWithResponses) GetMyReservationsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetMyReservationsResponse, error) {
	rsp, err := c.GetMyReservations(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMyReservationsResponse(rsp)
}

// GetReservationWithResponse request returning *GetReservationResponse
func (c *ClientWithResponses) GetReservationWithResponse(ctx context.Context, reservationId string, reqEditors ...RequestEditorFn) (*GetReservationResponse, error) {
	rsp, err := c.GetReservation(ctx, reservationId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetReservationResponse(rsp)
}

// DeleteReservationWithResponse request returning *DeleteReservationResponse
func (c *ClientWithResponses) DeleteReservationWithResponse(ctx context.Context, reservationId string, reqEditors ...RequestEditorFn) (*DeleteReservationResponse, error) {
	rsp, err := c.DeleteReservation(ctx, reservationId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteReservationResponse(rsp)
}

// UpdateReservationWithBodyWithResponse request with arbitrary body returning *UpdateReservationResponse
func (c *ClientWithResponses) UpdateReservationWithBodyWithResponse(ctx context.Context, reservationId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateReservationResponse, error) {
	rsp, err := c.UpdateReservationWithBody(ctx, reservationId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateReservationResponse(rsp)
}

func (c *ClientWithResponses) UpdateReservationWithResponse(ctx context.Context, reservationId string, body UpdateReservationJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateReservationResponse, error) {
	rsp, err := c.UpdateReservation(ctx, reservationId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateReservationResponse(rsp)
}

// GetRoomsWithResponse request returning *GetRoomsResponse
func (c *ClientWithResponses) GetRoomsWithResponse(ctx context.Context, params *GetRoomsParams, reqEditors ...RequestEditorFn) (*GetRoomsResponse, error) {
	rsp, err := c.GetRooms(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRoomsResponse(rsp)
}

// ParseAuthorizeResponse parses an HTTP response from a AuthorizeWithResponse call
func ParseAuthorizeResponse(rsp *http.Response) (*AuthorizeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AuthorizeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Code int           `json:"code"`
			Data Authorization `json:"data"`
			Ok   bool          `json:"ok"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateReservationResponse parses an HTTP response from a CreateReservationWithResponse call
func ParseCreateReservationResponse(rsp *http.Response) (*CreateReservationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateReservationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Response
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetMyReservationsResponse parses an HTTP response from a GetMyReservationsWithResponse call
func ParseGetMyReservationsResponse(rsp *http.Response) (*GetMyReservationsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMyReservationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Code int             `json:"code"`
			Data ReservationList `json:"data"`
			Ok   bool            `json:"ok"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetReservationResponse parses an HTTP response from a GetReservationWithResponse call
func ParseGetReservationResponse(rsp *http.Response) (*GetReservationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetReservationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Code int         `json:"code"`
			Data Reservation `json:"data"`
			Ok   bool        `json:"ok"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDeleteReservationResponse parses an HTTP response from a DeleteReservationWithResponse call
func ParseDeleteReservationResponse(rsp *http.Response) (*DeleteReservationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteReservationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Response
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseUpdateReservationResponse parses an HTTP response from a UpdateReservationWithResponse call
func ParseUpdateReservationResponse(rsp *http.Response) (*UpdateReservationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateReservationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Response
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetRoomsResponse parses an HTTP response from a GetRoomsWithResponse call
func ParseGetRoomsResponse(rsp *http.Response) (*GetRoomsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRoomsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Code int `json:"code"`
			Data struct {
				Rooms []Room `json:"rooms"`
			} `json:"data"`
			Ok bool `json:"ok"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ログイン
	// (POST /authorize)
	Authorize(ctx echo.Context) error
	// 予約の作成
	// (POST /reservations/create)
	CreateReservation(ctx echo.Context) error
	// 自分の予約を取得
	// (GET /reservations/mine)
	GetMyReservations(ctx echo.Context) error
	// 予約の取得
	// (GET /reservations/{reservation_id})
	GetReservation(ctx echo.Context, reservationId string) error
	// 予約の削除
	// (DELETE /reservations/{reservation_id}/delete)
	DeleteReservation(ctx echo.Context, reservationId string) error
	// 予約の更新
	// (PUT /reservations/{reservation_id}/update)
	UpdateReservation(ctx echo.Context, reservationId string) error
	// 練習室の取得
	// (GET /rooms)
	GetRooms(ctx echo.Context, params GetRoomsParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Authorize converts echo context to params.
func (w *ServerInterfaceWrapper) Authorize(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Authorize(ctx)
	return err
}

// CreateReservation converts echo context to params.
func (w *ServerInterfaceWrapper) CreateReservation(ctx echo.Context) error {
	var err error

	ctx.Set(BearerScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateReservation(ctx)
	return err
}

// GetMyReservations converts echo context to params.
func (w *ServerInterfaceWrapper) GetMyReservations(ctx echo.Context) error {
	var err error

	ctx.Set(BearerScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMyReservations(ctx)
	return err
}

// GetReservation converts echo context to params.
func (w *ServerInterfaceWrapper) GetReservation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "reservation_id" -------------
	var reservationId string

	err = runtime.BindStyledParameterWithOptions("simple", "reservation_id", ctx.Param("reservation_id"), &reservationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter reservation_id: %s", err))
	}

	ctx.Set(BearerScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetReservation(ctx, reservationId)
	return err
}

// DeleteReservation converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteReservation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "reservation_id" -------------
	var reservationId string

	err = runtime.BindStyledParameterWithOptions("simple", "reservation_id", ctx.Param("reservation_id"), &reservationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter reservation_id: %s", err))
	}

	ctx.Set(BearerScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteReservation(ctx, reservationId)
	return err
}

// UpdateReservation converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateReservation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "reservation_id" -------------
	var reservationId string

	err = runtime.BindStyledParameterWithOptions("simple", "reservation_id", ctx.Param("reservation_id"), &reservationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter reservation_id: %s", err))
	}

	ctx.Set(BearerScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateReservation(ctx, reservationId)
	return err
}

// GetRooms converts echo context to params.
func (w *ServerInterfaceWrapper) GetRooms(ctx echo.Context) error {
	var err error

	ctx.Set(BearerScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRoomsParams
	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameter("form", true, false, "id", ctx.QueryParams(), &params.Id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", ctx.QueryParams(), &params.Name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// ------------- Optional query parameter "piano_number" -------------

	err = runtime.BindQueryParameter("form", true, false, "piano_number", ctx.QueryParams(), &params.PianoNumber)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter piano_number: %s", err))
	}

	// ------------- Optional query parameter "piano_type" -------------

	err = runtime.BindQueryParameter("form", true, false, "piano_type", ctx.QueryParams(), &params.PianoType)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter piano_type: %s", err))
	}

	// ------------- Optional query parameter "floor" -------------

	err = runtime.BindQueryParameter("form", true, false, "floor", ctx.QueryParams(), &params.Floor)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter floor: %s", err))
	}

	// ------------- Optional query parameter "is_basement" -------------

	err = runtime.BindQueryParameter("form", true, false, "is_basement", ctx.QueryParams(), &params.IsBasement)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter is_basement: %s", err))
	}

	// ------------- Optional query parameter "campus_code" -------------

	err = runtime.BindQueryParameter("form", true, false, "campus_code", ctx.QueryParams(), &params.CampusCode)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter campus_code: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetRooms(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/authorize", wrapper.Authorize)
	router.POST(baseURL+"/reservations/create", wrapper.CreateReservation)
	router.GET(baseURL+"/reservations/mine", wrapper.GetMyReservations)
	router.GET(baseURL+"/reservations/:reservation_id", wrapper.GetReservation)
	router.DELETE(baseURL+"/reservations/:reservation_id/delete", wrapper.DeleteReservation)
	router.PUT(baseURL+"/reservations/:reservation_id/update", wrapper.UpdateReservation)
	router.GET(baseURL+"/rooms", wrapper.GetRooms)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYT28jNRT/Lobj0LTllht/JEBiL4s4VdXImXlJvI39XNtTFKoc6CIoXEB7WITg2BMS",
	"q5WohIQEfJhsWvgWaOxJxp7xJA1/Slfqbcb2++P3fu/3nnxKMuQSBQijSf+U6GwMnNrPNwozRsU+poah",
	"KBekQgnKMLDbNMtA69TgEdhdM5VA+kQbxcSIzBKiYKhAjztP2CPHBVOQk/5BqK8pfZgspXHwCDJT6n8I",
	"GtRJh3cZ5bLQaYY5lL8gCl4a2SMJ2fe01d7m1NiTQ1ScGtK3C68ZxoFETg8V8nexUN61mDAwArXcfcBE",
	"4TS291keDxgiTzv2DHabM9htrBFklpMkiE118dq4d7fgIisXPHsbsvI+06adGVUfsP/MALcfryoYkj55",
	"pVcjslfBsefneraySpWi09YdAwMdLkoUGiKoqeDSjnFODfV2amV45C0PECdARcslPCKVisTZiLqFyDcC",
	"OQK2CaIPDFHwwVqYMZ0OqAYOwsRctweyCdVaVQ61TwjKIapbMiowrVyIuutOuPVNlGDNJA60geZATcPh",
	"8IJNtLtotcM/S4iGrFDMTD8oMeeCPwCq3EUsEG0U3NJKwdgYSWalPBNDtHdiZlLumIwrfUIScgJKW5Ii",
	"ezu7O7sWNRIElYz0yes7uzslK0lqxtZmj1a86/CJroZKSFhIv5eT/oqabeHCcQHavIn51EFYmCqzVMoJ",
	"y6xU75F2LOkKqg0zSbX+CFUcMYUGFSemRsKWB5NaXyTUTsrVoDW+v7v7D1zfXLTrmCXsclsVdE2gNHrN",
	"hOSgM8Wka1EkQBnpHxwmRBecUzUlfTJ//OP87Pn87GL++Cd7sOfzWC9TUDWoOCLesvs+Tf5byBggHoFK",
	"O0s+3mn3kv06JGFKtmmzZbWGXSLS/oJm4JpWOl7bnFPebJgBPdLCYKphUuaxiyHXU6jPVtv6X1NbKLmc",
	"YUaKirLECqnYaFxSnEAB0aGmqXr9hNEMWrDXGbFGZUSHizolYfxrq76NVg7+Cw7ZMG24AeEGRVw3iYPD",
	"WVDRL345v778dP7Jsxe/fn91/nWkqDkTNqIjiFT0O2AeTB/6s8wdYs3mlHervNkd8j8+/2Fx/lkZchf7",
	"syeLr54ufvsmEvtT7y9l+WxdHkJalVRRDsYW9sEpYaWLZfcmy7mIhKqJHwKjCki8pDSL6fBuJvmuJHhV",
	"UzfOay+HCTjiqr/CDL9t11+iJN8idy2++PLPby9uEudCLnu7LCJl9KHdvu0g3w9A9wPQ/QD0f5PI1XeX",
	"V0+fVySC6LLZ2WztgTg5HBegpjU7WEboZoAkLlW9Kmwt13iBaMl7b27rFFRvFrX41rDu0u/eNv6OZ+GL",
	"SUvea/Zx+RDzravFufDWZ53GO+QSiDd7gETkm18ercrY295dmJ2uf768/v3J4tmFPz7NZn8FAAD//8jv",
	"PBsCGAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
