// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: user/v1/user.proto

package userv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/ekkx/tcmrsv-web/internal/shared/pb/user/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UserServiceName is the fully-qualified name of the UserService service.
	UserServiceName = "user.v1.UserService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserServiceGetUserProcedure is the fully-qualified name of the UserService's GetUser RPC.
	UserServiceGetUserProcedure = "/user.v1.UserService/GetUser"
	// UserServiceListSlaveUsersProcedure is the fully-qualified name of the UserService's
	// ListSlaveUsers RPC.
	UserServiceListSlaveUsersProcedure = "/user.v1.UserService/ListSlaveUsers"
	// UserServiceCreateSlaveUserProcedure is the fully-qualified name of the UserService's
	// CreateSlaveUser RPC.
	UserServiceCreateSlaveUserProcedure = "/user.v1.UserService/CreateSlaveUser"
	// UserServiceUpdateUserProcedure is the fully-qualified name of the UserService's UpdateUser RPC.
	UserServiceUpdateUserProcedure = "/user.v1.UserService/UpdateUser"
	// UserServiceDeleteUserProcedure is the fully-qualified name of the UserService's DeleteUser RPC.
	UserServiceDeleteUserProcedure = "/user.v1.UserService/DeleteUser"
)

// UserServiceClient is a client for the user.v1.UserService service.
type UserServiceClient interface {
	GetUser(context.Context, *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.GetUserResponse], error)
	ListSlaveUsers(context.Context, *connect.Request[v1.ListSlaveUsersRequest]) (*connect.Response[v1.ListSlaveUsersResponse], error)
	CreateSlaveUser(context.Context, *connect.Request[v1.CreateSlaveUserRequest]) (*connect.Response[v1.CreateSlaveUserResponse], error)
	UpdateUser(context.Context, *connect.Request[v1.UpdateUserRequest]) (*connect.Response[v1.UpdateUserResponse], error)
	DeleteUser(context.Context, *connect.Request[v1.DeleteUserRequest]) (*connect.Response[v1.DeleteUserResponse], error)
}

// NewUserServiceClient constructs a client for the user.v1.UserService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	userServiceMethods := v1.File_user_v1_user_proto.Services().ByName("UserService").Methods()
	return &userServiceClient{
		getUser: connect.NewClient[v1.GetUserRequest, v1.GetUserResponse](
			httpClient,
			baseURL+UserServiceGetUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("GetUser")),
			connect.WithClientOptions(opts...),
		),
		listSlaveUsers: connect.NewClient[v1.ListSlaveUsersRequest, v1.ListSlaveUsersResponse](
			httpClient,
			baseURL+UserServiceListSlaveUsersProcedure,
			connect.WithSchema(userServiceMethods.ByName("ListSlaveUsers")),
			connect.WithClientOptions(opts...),
		),
		createSlaveUser: connect.NewClient[v1.CreateSlaveUserRequest, v1.CreateSlaveUserResponse](
			httpClient,
			baseURL+UserServiceCreateSlaveUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("CreateSlaveUser")),
			connect.WithClientOptions(opts...),
		),
		updateUser: connect.NewClient[v1.UpdateUserRequest, v1.UpdateUserResponse](
			httpClient,
			baseURL+UserServiceUpdateUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("UpdateUser")),
			connect.WithClientOptions(opts...),
		),
		deleteUser: connect.NewClient[v1.DeleteUserRequest, v1.DeleteUserResponse](
			httpClient,
			baseURL+UserServiceDeleteUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("DeleteUser")),
			connect.WithClientOptions(opts...),
		),
	}
}

// userServiceClient implements UserServiceClient.
type userServiceClient struct {
	getUser         *connect.Client[v1.GetUserRequest, v1.GetUserResponse]
	listSlaveUsers  *connect.Client[v1.ListSlaveUsersRequest, v1.ListSlaveUsersResponse]
	createSlaveUser *connect.Client[v1.CreateSlaveUserRequest, v1.CreateSlaveUserResponse]
	updateUser      *connect.Client[v1.UpdateUserRequest, v1.UpdateUserResponse]
	deleteUser      *connect.Client[v1.DeleteUserRequest, v1.DeleteUserResponse]
}

// GetUser calls user.v1.UserService.GetUser.
func (c *userServiceClient) GetUser(ctx context.Context, req *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.GetUserResponse], error) {
	return c.getUser.CallUnary(ctx, req)
}

// ListSlaveUsers calls user.v1.UserService.ListSlaveUsers.
func (c *userServiceClient) ListSlaveUsers(ctx context.Context, req *connect.Request[v1.ListSlaveUsersRequest]) (*connect.Response[v1.ListSlaveUsersResponse], error) {
	return c.listSlaveUsers.CallUnary(ctx, req)
}

// CreateSlaveUser calls user.v1.UserService.CreateSlaveUser.
func (c *userServiceClient) CreateSlaveUser(ctx context.Context, req *connect.Request[v1.CreateSlaveUserRequest]) (*connect.Response[v1.CreateSlaveUserResponse], error) {
	return c.createSlaveUser.CallUnary(ctx, req)
}

// UpdateUser calls user.v1.UserService.UpdateUser.
func (c *userServiceClient) UpdateUser(ctx context.Context, req *connect.Request[v1.UpdateUserRequest]) (*connect.Response[v1.UpdateUserResponse], error) {
	return c.updateUser.CallUnary(ctx, req)
}

// DeleteUser calls user.v1.UserService.DeleteUser.
func (c *userServiceClient) DeleteUser(ctx context.Context, req *connect.Request[v1.DeleteUserRequest]) (*connect.Response[v1.DeleteUserResponse], error) {
	return c.deleteUser.CallUnary(ctx, req)
}

// UserServiceHandler is an implementation of the user.v1.UserService service.
type UserServiceHandler interface {
	GetUser(context.Context, *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.GetUserResponse], error)
	ListSlaveUsers(context.Context, *connect.Request[v1.ListSlaveUsersRequest]) (*connect.Response[v1.ListSlaveUsersResponse], error)
	CreateSlaveUser(context.Context, *connect.Request[v1.CreateSlaveUserRequest]) (*connect.Response[v1.CreateSlaveUserResponse], error)
	UpdateUser(context.Context, *connect.Request[v1.UpdateUserRequest]) (*connect.Response[v1.UpdateUserResponse], error)
	DeleteUser(context.Context, *connect.Request[v1.DeleteUserRequest]) (*connect.Response[v1.DeleteUserResponse], error)
}

// NewUserServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserServiceHandler(svc UserServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userServiceMethods := v1.File_user_v1_user_proto.Services().ByName("UserService").Methods()
	userServiceGetUserHandler := connect.NewUnaryHandler(
		UserServiceGetUserProcedure,
		svc.GetUser,
		connect.WithSchema(userServiceMethods.ByName("GetUser")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceListSlaveUsersHandler := connect.NewUnaryHandler(
		UserServiceListSlaveUsersProcedure,
		svc.ListSlaveUsers,
		connect.WithSchema(userServiceMethods.ByName("ListSlaveUsers")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceCreateSlaveUserHandler := connect.NewUnaryHandler(
		UserServiceCreateSlaveUserProcedure,
		svc.CreateSlaveUser,
		connect.WithSchema(userServiceMethods.ByName("CreateSlaveUser")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceUpdateUserHandler := connect.NewUnaryHandler(
		UserServiceUpdateUserProcedure,
		svc.UpdateUser,
		connect.WithSchema(userServiceMethods.ByName("UpdateUser")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceDeleteUserHandler := connect.NewUnaryHandler(
		UserServiceDeleteUserProcedure,
		svc.DeleteUser,
		connect.WithSchema(userServiceMethods.ByName("DeleteUser")),
		connect.WithHandlerOptions(opts...),
	)
	return "/user.v1.UserService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserServiceGetUserProcedure:
			userServiceGetUserHandler.ServeHTTP(w, r)
		case UserServiceListSlaveUsersProcedure:
			userServiceListSlaveUsersHandler.ServeHTTP(w, r)
		case UserServiceCreateSlaveUserProcedure:
			userServiceCreateSlaveUserHandler.ServeHTTP(w, r)
		case UserServiceUpdateUserProcedure:
			userServiceUpdateUserHandler.ServeHTTP(w, r)
		case UserServiceDeleteUserProcedure:
			userServiceDeleteUserHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUserServiceHandler struct{}

func (UnimplementedUserServiceHandler) GetUser(context.Context, *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.GetUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.v1.UserService.GetUser is not implemented"))
}

func (UnimplementedUserServiceHandler) ListSlaveUsers(context.Context, *connect.Request[v1.ListSlaveUsersRequest]) (*connect.Response[v1.ListSlaveUsersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.v1.UserService.ListSlaveUsers is not implemented"))
}

func (UnimplementedUserServiceHandler) CreateSlaveUser(context.Context, *connect.Request[v1.CreateSlaveUserRequest]) (*connect.Response[v1.CreateSlaveUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.v1.UserService.CreateSlaveUser is not implemented"))
}

func (UnimplementedUserServiceHandler) UpdateUser(context.Context, *connect.Request[v1.UpdateUserRequest]) (*connect.Response[v1.UpdateUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.v1.UserService.UpdateUser is not implemented"))
}

func (UnimplementedUserServiceHandler) DeleteUser(context.Context, *connect.Request[v1.DeleteUserRequest]) (*connect.Response[v1.DeleteUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.v1.UserService.DeleteUser is not implemented"))
}
