// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file room/v1/room.proto (package room.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file room/v1/room.proto.
 */
export const file_room_v1_room: GenFile = /*@__PURE__*/
  fileDesc("ChJyb29tL3YxL3Jvb20ucHJvdG8SB3Jvb20udjEiwQEKBFJvb20SCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRImCgpwaWFub190eXBlGAMgASgOMhIucm9vbS52MS5QaWFub1R5cGUSEwoLcGlhbm9fY291bnQYBCABKAUSFAoMaXNfY2xhc3Nyb29tGAUgASgIEhMKC2lzX2Jhc2VtZW50GAYgASgIEigKC2NhbXB1c190eXBlGAcgASgOMhMucm9vbS52MS5DYW1wdXNUeXBlEg0KBWZsb29yGAggASgFIp8BChlMaXN0QXZhaWxhYmxlUm9vbXNSZXF1ZXN0EigKC2NhbXB1c190eXBlGAEgASgOMhMucm9vbS52MS5DYW1wdXNUeXBlEgwKBGRhdGUYAiABKAkSEQoJZnJvbV9ob3VyGAMgASgFEhMKC2Zyb21fbWludXRlGAQgASgFEg8KB3RvX2hvdXIYBSABKAUSEQoJdG9fbWludXRlGAYgASgFIjoKGkxpc3RBdmFpbGFibGVSb29tc1Jlc3BvbnNlEhwKBXJvb21zGAEgAygLMg0ucm9vbS52MS5Sb29tKmAKCkNhbXB1c1R5cGUSGwoXQ0FNUFVTX1RZUEVfVU5TUEVDSUZJRUQQABIaChZDQU1QVVNfVFlQRV9OQUtBTUVHVVJPEAESGQoVQ0FNUFVTX1RZUEVfSUtFQlVLVVJPEAIqagoJUGlhbm9UeXBlEhoKFlBJQU5PX1RZUEVfVU5TUEVDSUZJRUQQABIUChBQSUFOT19UWVBFX0dSQU5EEAESFgoSUElBTk9fVFlQRV9VUFJJR0hUEAISEwoPUElBTk9fVFlQRV9OT05FEAMybAoLUm9vbVNlcnZpY2USXQoSTGlzdEF2YWlsYWJsZVJvb21zEiIucm9vbS52MS5MaXN0QXZhaWxhYmxlUm9vbXNSZXF1ZXN0GiMucm9vbS52MS5MaXN0QXZhaWxhYmxlUm9vbXNSZXNwb25zZUKaAQoLY29tLnJvb20udjFCCVJvb21Qcm90b1ABWkNnaXRodWIuY29tL2Vra3gvdGNtcnN2LXdlYi9zZXJ2ZXIvaW50ZXJuYWwvc2hhcmVkL3BiL3Jvb20vdjE7cm9vbXYxogIDUlhYqgIHUm9vbS5WMcoCB1Jvb21cVjHiAhNSb29tXFYxXEdQQk1ldGFkYXRh6gIIUm9vbTo6VjFiBnByb3RvMw");

/**
 * @generated from message room.v1.Room
 */
export type Room = Message<"room.v1.Room"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: room.v1.PianoType piano_type = 3;
   */
  pianoType: PianoType;

  /**
   * @generated from field: int32 piano_count = 4;
   */
  pianoCount: number;

  /**
   * @generated from field: bool is_classroom = 5;
   */
  isClassroom: boolean;

  /**
   * @generated from field: bool is_basement = 6;
   */
  isBasement: boolean;

  /**
   * @generated from field: room.v1.CampusType campus_type = 7;
   */
  campusType: CampusType;

  /**
   * @generated from field: int32 floor = 8;
   */
  floor: number;
};

/**
 * Describes the message room.v1.Room.
 * Use `create(RoomSchema)` to create a new message.
 */
export const RoomSchema: GenMessage<Room> = /*@__PURE__*/
  messageDesc(file_room_v1_room, 0);

/**
 * @generated from message room.v1.ListAvailableRoomsRequest
 */
export type ListAvailableRoomsRequest = Message<"room.v1.ListAvailableRoomsRequest"> & {
  /**
   * @generated from field: room.v1.CampusType campus_type = 1;
   */
  campusType: CampusType;

  /**
   * @generated from field: string date = 2;
   */
  date: string;

  /**
   * @generated from field: int32 from_hour = 3;
   */
  fromHour: number;

  /**
   * @generated from field: int32 from_minute = 4;
   */
  fromMinute: number;

  /**
   * @generated from field: int32 to_hour = 5;
   */
  toHour: number;

  /**
   * @generated from field: int32 to_minute = 6;
   */
  toMinute: number;
};

/**
 * Describes the message room.v1.ListAvailableRoomsRequest.
 * Use `create(ListAvailableRoomsRequestSchema)` to create a new message.
 */
export const ListAvailableRoomsRequestSchema: GenMessage<ListAvailableRoomsRequest> = /*@__PURE__*/
  messageDesc(file_room_v1_room, 1);

/**
 * @generated from message room.v1.ListAvailableRoomsResponse
 */
export type ListAvailableRoomsResponse = Message<"room.v1.ListAvailableRoomsResponse"> & {
  /**
   * @generated from field: repeated room.v1.Room rooms = 1;
   */
  rooms: Room[];
};

/**
 * Describes the message room.v1.ListAvailableRoomsResponse.
 * Use `create(ListAvailableRoomsResponseSchema)` to create a new message.
 */
export const ListAvailableRoomsResponseSchema: GenMessage<ListAvailableRoomsResponse> = /*@__PURE__*/
  messageDesc(file_room_v1_room, 2);

/**
 * @generated from enum room.v1.CampusType
 */
export enum CampusType {
  /**
   * @generated from enum value: CAMPUS_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CAMPUS_TYPE_NAKAMEGURO = 1;
   */
  NAKAMEGURO = 1,

  /**
   * @generated from enum value: CAMPUS_TYPE_IKEBUKURO = 2;
   */
  IKEBUKURO = 2,
}

/**
 * Describes the enum room.v1.CampusType.
 */
export const CampusTypeSchema: GenEnum<CampusType> = /*@__PURE__*/
  enumDesc(file_room_v1_room, 0);

/**
 * @generated from enum room.v1.PianoType
 */
export enum PianoType {
  /**
   * @generated from enum value: PIANO_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: PIANO_TYPE_GRAND = 1;
   */
  GRAND = 1,

  /**
   * @generated from enum value: PIANO_TYPE_UPRIGHT = 2;
   */
  UPRIGHT = 2,

  /**
   * @generated from enum value: PIANO_TYPE_NONE = 3;
   */
  NONE = 3,
}

/**
 * Describes the enum room.v1.PianoType.
 */
export const PianoTypeSchema: GenEnum<PianoType> = /*@__PURE__*/
  enumDesc(file_room_v1_room, 1);

/**
 * @generated from service room.v1.RoomService
 */
export const RoomService: GenService<{
  /**
   * @generated from rpc room.v1.RoomService.ListAvailableRooms
   */
  listAvailableRooms: {
    methodKind: "unary";
    input: typeof ListAvailableRoomsRequestSchema;
    output: typeof ListAvailableRoomsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_room_v1_room, 0);

