// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file auth/v1/auth.proto (package auth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { User } from "../../user/v1/user_pb";
import { file_user_v1_user } from "../../user/v1/user_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file auth/v1/auth.proto.
 */
export const file_auth_v1_auth: GenFile = /*@__PURE__*/
  fileDesc("ChJhdXRoL3YxL2F1dGgucHJvdG8SB2F1dGgudjEiUAoEQXV0aBIUCgxhY2Nlc3NfdG9rZW4YASABKAkSFQoNcmVmcmVzaF90b2tlbhgCIAEoCRIbCgR1c2VyGAMgASgLMg0udXNlci52MS5Vc2VyIjUKEEF1dGhvcml6ZVJlcXVlc3QSDwoHdXNlcl9pZBgBIAEoCRIQCghwYXNzd29yZBgCIAEoCSIwChFBdXRob3JpemVSZXNwb25zZRIbCgRhdXRoGAEgASgLMg0uYXV0aC52MS5BdXRoIisKElJlYXV0aG9yaXplUmVxdWVzdBIVCg1yZWZyZXNoX3Rva2VuGAIgASgJIjIKE1JlYXV0aG9yaXplUmVzcG9uc2USGwoEYXV0aBgBIAEoCzINLmF1dGgudjEuQXV0aCJDChVVcGRhdGVQYXNzd29yZFJlcXVlc3QSFAoMb2xkX3Bhc3N3b3JkGAIgASgJEhQKDG5ld19wYXNzd29yZBgDIAEoCSIYChZVcGRhdGVQYXNzd29yZFJlc3BvbnNlMu4BCgtBdXRoU2VydmljZRJCCglBdXRob3JpemUSGS5hdXRoLnYxLkF1dGhvcml6ZVJlcXVlc3QaGi5hdXRoLnYxLkF1dGhvcml6ZVJlc3BvbnNlEkgKC1JlYXV0aG9yaXplEhsuYXV0aC52MS5SZWF1dGhvcml6ZVJlcXVlc3QaHC5hdXRoLnYxLlJlYXV0aG9yaXplUmVzcG9uc2USUQoOVXBkYXRlUGFzc3dvcmQSHi5hdXRoLnYxLlVwZGF0ZVBhc3N3b3JkUmVxdWVzdBofLmF1dGgudjEuVXBkYXRlUGFzc3dvcmRSZXNwb25zZUKTAQoLY29tLmF1dGgudjFCCUF1dGhQcm90b1ABWjxnaXRodWIuY29tL2Vra3gvdGNtcnN2LXdlYi9pbnRlcm5hbC9zaGFyZWQvcGIvYXV0aC92MTthdXRodjGiAgNBWFiqAgdBdXRoLlYxygIHQXV0aFxWMeICE0F1dGhcVjFcR1BCTWV0YWRhdGHqAghBdXRoOjpWMWIGcHJvdG8z", [file_user_v1_user]);

/**
 * @generated from message auth.v1.Auth
 */
export type Auth = Message<"auth.v1.Auth"> & {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * @generated from field: string refresh_token = 2;
   */
  refreshToken: string;

  /**
   * @generated from field: user.v1.User user = 3;
   */
  user?: User;
};

/**
 * Describes the message auth.v1.Auth.
 * Use `create(AuthSchema)` to create a new message.
 */
export const AuthSchema: GenMessage<Auth> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 0);

/**
 * @generated from message auth.v1.AuthorizeRequest
 */
export type AuthorizeRequest = Message<"auth.v1.AuthorizeRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message auth.v1.AuthorizeRequest.
 * Use `create(AuthorizeRequestSchema)` to create a new message.
 */
export const AuthorizeRequestSchema: GenMessage<AuthorizeRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 1);

/**
 * @generated from message auth.v1.AuthorizeResponse
 */
export type AuthorizeResponse = Message<"auth.v1.AuthorizeResponse"> & {
  /**
   * @generated from field: auth.v1.Auth auth = 1;
   */
  auth?: Auth;
};

/**
 * Describes the message auth.v1.AuthorizeResponse.
 * Use `create(AuthorizeResponseSchema)` to create a new message.
 */
export const AuthorizeResponseSchema: GenMessage<AuthorizeResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 2);

/**
 * @generated from message auth.v1.ReauthorizeRequest
 */
export type ReauthorizeRequest = Message<"auth.v1.ReauthorizeRequest"> & {
  /**
   * @generated from field: string refresh_token = 2;
   */
  refreshToken: string;
};

/**
 * Describes the message auth.v1.ReauthorizeRequest.
 * Use `create(ReauthorizeRequestSchema)` to create a new message.
 */
export const ReauthorizeRequestSchema: GenMessage<ReauthorizeRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 3);

/**
 * @generated from message auth.v1.ReauthorizeResponse
 */
export type ReauthorizeResponse = Message<"auth.v1.ReauthorizeResponse"> & {
  /**
   * @generated from field: auth.v1.Auth auth = 1;
   */
  auth?: Auth;
};

/**
 * Describes the message auth.v1.ReauthorizeResponse.
 * Use `create(ReauthorizeResponseSchema)` to create a new message.
 */
export const ReauthorizeResponseSchema: GenMessage<ReauthorizeResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 4);

/**
 * @generated from message auth.v1.UpdatePasswordRequest
 */
export type UpdatePasswordRequest = Message<"auth.v1.UpdatePasswordRequest"> & {
  /**
   * @generated from field: string old_password = 2;
   */
  oldPassword: string;

  /**
   * @generated from field: string new_password = 3;
   */
  newPassword: string;
};

/**
 * Describes the message auth.v1.UpdatePasswordRequest.
 * Use `create(UpdatePasswordRequestSchema)` to create a new message.
 */
export const UpdatePasswordRequestSchema: GenMessage<UpdatePasswordRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 5);

/**
 * @generated from message auth.v1.UpdatePasswordResponse
 */
export type UpdatePasswordResponse = Message<"auth.v1.UpdatePasswordResponse"> & {
};

/**
 * Describes the message auth.v1.UpdatePasswordResponse.
 * Use `create(UpdatePasswordResponseSchema)` to create a new message.
 */
export const UpdatePasswordResponseSchema: GenMessage<UpdatePasswordResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 6);

/**
 * @generated from service auth.v1.AuthService
 */
export const AuthService: GenService<{
  /**
   * @generated from rpc auth.v1.AuthService.Authorize
   */
  authorize: {
    methodKind: "unary";
    input: typeof AuthorizeRequestSchema;
    output: typeof AuthorizeResponseSchema;
  },
  /**
   * @generated from rpc auth.v1.AuthService.Reauthorize
   */
  reauthorize: {
    methodKind: "unary";
    input: typeof ReauthorizeRequestSchema;
    output: typeof ReauthorizeResponseSchema;
  },
  /**
   * @generated from rpc auth.v1.AuthService.UpdatePassword
   */
  updatePassword: {
    methodKind: "unary";
    input: typeof UpdatePasswordRequestSchema;
    output: typeof UpdatePasswordResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_auth_v1_auth, 0);

